### ISSUE TITLE
medyanetads.com

### ISSUE THREAD

**Issue by norilana** [hagezi/dns-blocklists#1007]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### Other

              o.o

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi ULTIMATE

### Which domain(s) should be unblocked?

medyanetads.com

### Why should the domain(s) be unblocked?

Breaks site layout on `www.gazetevatan.com`

**Comment by hagezi** [comment]
Ultimate, no whitelisting:

![grafik](https://user-images.githubusercontent.com/104343908/236268198-12ebcdb1-375a-4da7-8281-96249dd65a51.png)

![grafik](https://user-images.githubusercontent.com/104343908/236268918-0e776ca2-6efe-43ac-b224-42969c8c2100.png)

**Comment by hagezi** [comment]
@norilana Blockpage in NextDNS enabled?

**Comment by hagezi** [comment]
NextDNS Ultimate, no whitelisting:

![grafik](https://user-images.githubusercontent.com/104343908/236275815-59aaaf83-d716-4d36-9c78-2df0e5e449d6.png)

![grafik](https://user-images.githubusercontent.com/104343908/236275977-84228ff4-e778-41ff-befe-052813eb0cea.png)

**Comment by hagezi** [comment]
I can't reproduce it, can you check if allowing `cdn.medyanetads.com` is enough?

**Comment by hagezi** [comment]
OK, thanks.

**Comment by hagezi** [comment]
@symbuzzer: Can you please check and confirm the behaviour? I cannot reproduce this in my region.

Use of many fingerprinting APIs:
https://slayterdev.github.io/tracker-radar-wiki/domains/medyanetads.com.html

**Comment by hagezi** [comment]
@symbuzzer many thanks for your assistance!

**Comment by symbuzzer** [comment]
![image](https://user-images.githubusercontent.com/9841184/236299472-2ab9cab3-2c72-4166-8116-62f9dfbcdf44.png)
![photo_5954276865579531174_y](https://user-images.githubusercontent.com/9841184/236299612-9cf2dbb6-139e-4093-a004-111fb8fb9010.jpg)

Tested both Windows PC and Android mobile. Blocking ad.medyanetads.com and cdn.medyanetads.com does not cause any problems in loading the site and blocks all ads on the site.

However, it is possible that the user reporting the error is using a cloudflare-based vpn service. Because when I tried to access the site with Proton VPN, I had the same problem.

**Comment by hagezi** [comment]
Thanks @symbuzzer, ping @norilana.

**Comment by symbuzzer** [comment]
> You should check the site in detail without using an ad-blocker.

Already tested. But why does it need to be tested? What do I need to catch? I really don't understand...

**Comment by hagezi** [comment]
@norilana Two people have tested the site now and none can reproduce the problem. As I am in a different region, I have asked @symbuzze to test. He could only reproduce it when he accessed the page via Proton VPN. Without VPN, he has no problems, just like me.

So it's not generally due to the blocked domains. Something is different in your case.

I see no reason to unblock the domains, they are fingerprinting trackers and provides ads.
They are used on the following sites:

```
hurriyet.com.tr
bigpara.hurriyet.com.tr
cnnturk.com
fanatik.com.tr
gazetevatan.com
kanald.com.tr
milliyet.com.tr
posta.com.tr
```

Put the domains on your personal Allowlist.

**Comment by hagezi** [comment]
No problem @norilana. Thanks again for your assistance @symbuzzer.
