### ISSUE TITLE
Why not blocking several Microsoft services?

### ISSUE THREAD

**Issue by pictosun** [hagezi/dns-blocklists#103]
Hi,

as there is nearly no detailed information and some lists are blocking it and others don't.... Your lists don't block:
nexusrules.officeapps.live.com
self.events.data.microsoft.com

Any reason why you don't block them?

Thx.

**Comment by hagezi** [comment]
Yes, this breaks Office 365 online.

**Comment by pictosun** [comment]
Ok. Thx for the feedback. 

For me I do have nearly 1000 requests to eu-mobile.events.data.microsoft.com for example (when OneDrive turned on within macOS). For me it sounds like a tracking domain (or something really clever from Microsoft).

**Comment by hagezi** [comment]
`eu-mobile.events.data.microsoft.com`is blocked in all lists.

![grafik](https://user-images.githubusercontent.com/104343908/207258997-2055a64e-8996-40b8-a225-6b27966d2270.png)

Unblocked were only `nexusrules.officeapps.live.com` and `self.events.data.microsoft.com`. They prevent the use of the Office Admin Center, hinder the collaboration of several people on one document and cause problems when saving documents online.

If you do not use Office 365 online, blacklist these domains or use Ultimate.

Currently, `browser.events.data.microsoft.com` has been unblocked because the use of Office Forms does not work otherwise. But it is still blocked in Ultimate.

**Comment by hagezi** [comment]
Oops, just saw that `eu-mobile.events.data.microsoft.com` is missing from my native list. I'll fix that.

**Comment by hagezi** [comment]
`*-mobile.events.data.microsoft.com` added to native list. Other lists will be updated on next update. Thanks for the advice!
