### ISSUE TITLE
Sorting request for Bypass DNS list

### ISSUE THREAD

**Issue by RicoHeat** [hagezi/dns-blocklists#1104]
Hello my friend @hagezi 
Not an issue just a request for https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/doh-vpn-proxy-bypass.txt

Would it be possible to sort out the list according to groups like Google etc..?

Thought that it would be great for users to quickly identify any possible links that they may possibly want to whitelist.

Well its just a thought.. Thanks for your amazing work.. 👍

Have a great day!

**Comment by hagezi** [comment]
The lists are generated and sorted by domain (within a rule from the back to the front), so that what belongs together is actually below each other, for example

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/8c056b49-81c7-4694-9bf6-f3e2f53a3007)

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/d9ac9884-ee14-4062-98c5-9e611b3d4787)

Sorting them by provider means some effort, as I said, the lists are generated from sources.
