### ISSUE TITLE
DoH/VPN/TOR/Proxy Bypass - Prevent methods to bypass your DNS!

### ISSUE THREAD

**Issue by Freebase394** [hagezi/dns-blocklists#1324]
### Which domain(s) should be blocked?

Could someone add this adresses to Block On "ProtonVPN"

Using Free Tier VPN Servers:

vpn-api.proton.me
protonstatus.com
protonvpn.ch
protonvpn.com
protonvpn.net
api.protonvpn.ch
protonvpn.com

regexr.com/7h9kc

### Why should these domain(s) be blocked?

If I add this list "https://github.com/hagezi/dns-blocklists#bypass" 
I am still able to connect to the VPN, when this should not happen, because by default it does not have all the domains.

**Comment by hagezi** [comment]
@Freebase394 

Please note, this list does not include subdomains and is therefore only suitable for AdBlockers that support wildcard blocking:

Example: 

```
protonvpn.ch
api.protonvpn.ch
```

Only `protonvpn.ch` is on the list because wildcard blocking automatically blocks all subdomains.

The following table shows which AdBlockers are compatible: https://github.com/hagezi/dns-blocklists#bypass
