### ISSUE TITLE
Proposed domains for blocking

### ISSUE THREAD

**Issue by rafalfr** [hagezi/dns-blocklists#1409]
### Which domain(s) should be blocked?

Please consider blocking device-api.urbanairship.com, analytics.twitter.com, api.onesignal.com, csi.gstatic.com, ybp.yahoo.com, c.amazon-adsystem.com, alb.reddit.com
On my android device, duckduckgo App tracking protection reports this domains as a trackers.

### Why should these domain(s) be blocked?

They are listed in the file 
[android-tds.json](https://github.com/duckduckgo/tracker-blocklists/blob/main/app/android-tds.json)

https://github.com/duckduckgo/tracker-blocklists/blob/main/app/README.md

**Comment by hagezi** [comment]
Hi @rafalfr,

thanks, but there are exceptions for these domains, which is why they are not blocked in my DNS lists. 

Blocking domains with multiple exceptions is reserved for content blockers because they can decide on which page they are blocked and on which they are not. What is not possible with DNS, blocked is blocked, for all pages. That is the other side of the DNS coin. That's why you should also use a content blocker like uBlock in addition to the DNS blocker.

If you are not restricted by the domains, you can put them on your personal denylist. But I can't block them for the masses.

**Comment by hagezi** [comment]
@rafalfr details:

`alb.reddit.com` - Referrel domain, breaks reddit link clicking
`analytics.twitter.com` - Referral domain, breaks tweet link clicking
`ybp.yahoo.com` - NXDOMAIN, subdomains blocked
`c.amazon-adsystem.com` - breaks videos on some sites, e.g. CNN
`device-api.urbanairship.com` - only in aggressive lists
`api.onesignal.com` - only in aggressive lists
`csi.gstatic.com` - https://github.com/search?q=csi.gstatic.com&type=issues
