### ISSUE TITLE
Apple analytics

### ISSUE THREAD

**Issue by lthedetective** [hagezi/dns-blocklists#1609]
### Which domain(s) should be blocked?

xp.apple.com

### Why should these domain(s) be blocked?

these are apple music analytics for android

**Comment by iam-py-test** [comment]
Oddly it's listed in the native tracker list: https://github.com/hagezi/dns-blocklists/blob/main/wildcard/native.apple-onlydomains.txt#L22

**Comment by hagezi** [comment]
Yes, it is tracking and therefore in the native list. However, it was removed from the other block lists because there are problems with updates on some devices, in certain regions and depending on the humidity. Some have problems, others don't.

I have blocked it in my area and unblock it when there are problems. But I haven't had any problems with the last updates.
Yes, it is tracking and therefore in the native list. However, it was removed from the other block lists because there are problems with updates on some devices, in certain regions and depending on the humidity. Some have problems, others don't.
I have blocked it in my area and unblock it when there are problems. But I haven't had any problems with the last updates.

If I add it to the other block lists again, the screaming starts again after a short time.
