### ISSUE TITLE
Add support for differential updates

### ISSUE THREAD

**Issue by adworacz** [hagezi/dns-blocklists#1934]
Per the [1.5.4.0](https://github.com/gorhill/uBlock/releases/tag/1.54.0) release to uBlock Origin, a new download approach for filter list updates has been introduced that provides diff/partial updates.

The official standard for said updates lives here: https://github.com/ameshkov/diffupdates

This may lead to a significant reduction in bandwidth for projects that update to support this standard (which likely will be Adguard products ASAP, since the standard is written by an Adguard contributor, as well as uBlock Origin, etc).

**Comment by hagezi** [comment]
Hi, I'd like to have a look at how this can be integrated into my build system. However, my lists are DNS lists, so far there are no pure DNS blockers that support this.

I'll have a look when I have more time to prioritise, but that won't happen this year.

**Comment by adworacz** [comment]
I've opened a ticket with AdguardHome about supporting this feature: https://github.com/AdguardTeam/AdGuardHome/issues/6543

**Comment by lynxthecat** [comment]
I think one easy way to help reduce server strain is thundering herd prevention in which clients are configured to download the blocklists at different times (e.g. random number of minutes past an hour).

**Comment by iam-py-test** [comment]
I can not speak for all content blockers, but in uBlock Origin, when a filterlist is updated depends on when it was last updated (or added), so updates should already be spread out. Filterlists are updated every day/_x number of days_ rather than at a fixed time of day.
(sorry if this is confusingly written).
Thanks

**Comment by adworacz** [comment]
@lynxthecat Your suggestion, while a good one, seems better suited for blocklist consumers (uBlock Origin, Adguard Home, etc) instead of blocklist producers (Hagezi), as the former is what actually controls the rate of downloads.

Have you tried suggesting said feature to your blocklist consumer?

**Comment by lynxthecat** [comment]
https://github.com/lynxthecat/adblock-lean

**Comment by lynxthecat** [comment]
I see the benefit in differential updates but implementing it in the right way might be tricky and of course all downstream applications have to be altered to work with whatever common format is used (and not all consumer applications will want to restrict exclusively to Hagezi so then the common format has to be agreed with the other popular lists or there a potential mismatch there).

However I think consideration might also usefully be afforded to:

- simply placing a note on the README requesting that consumer applications implement some form of thundering herd prevention; 

- offering up lists in compressed .gz form. 

Personally I'm not especially bothered since the lists are not that huge already (circa 25Mb per night in my case).

**Comment by hagezi** [comment]
I have now taken a closer look at this, I would have to rebuild my entire build system. For me, the cost-benefit ratio is not reasonable. Furthermore, it is not yet supported by DNS blockers and I don't think it will be implemented in the near future.

My lists are usually updated every 24 hours, so I don't see a download of a few MB a day as a problem.

I'm closing the issue and if it becomes relevant again at some point, we'll dig it up again.

**Comment by adworacz** [comment]
I’d say that’s totally fair. Thank you for considering it.
