### ISSUE TITLE
weebly.com

### ISSUE THREAD

**Issue by devipasigner** [hagezi/dns-blocklists#204]
Not sure why this is blocked on the pro list. Probably too strict for the standard pro list.

**Comment by hagezi** [comment]
Weebly is on the lists because it is a free hoster that also hosts "badware". To reduce the size of the compressed lists, the FLD is on the list. This eliminates 100s of subdomain rules and possible - new - subdomains are automatically blocked.

On the Umbrella Toplist, there are just 36 weebly subdomains that are not classified as badware. In contrast, there are 2071 badware subdomains on the hosts version of the Ultimate version.

**Comment by devipasigner** [comment]
> Weebly is on the lists because it is a free hoster that also hosts "badware". To reduce the size of the compressed lists, the FLD is on the list. This eliminates 100s of subdomain rules and possible - new - subdomains are automatically blocked.
> 
> On the Umbrella Toplist, there are just 36 weebly subdomains that are not classified as badware. In contrast, there are 2071 badware subdomains on the hosts version of the Ultimate version.

Hmm, I can understand your point of view. IMO, only ultimate should include hoster + ddns, otherwise it’s up to the user. However I wish that all blocklists used the same sources but just different level of whitelisting. I want to benefit from more coverage while not being too strict. Because honestly I don’t think your lists have much difference in terms of strictness, just more coverage in each list.

**Comment by hagezi** [comment]
Strictness for Light to Pro are almost identical. They differ in size. The size comes mostly from malware, scam, phishing and other domains from this category.
They are mostly generated from balanced sources. Except for the Pro, because it includes the NoTracking list and this one is a bit more aggressive in some areas.
The differentiation of the size serves to make the lists compatible also for AdBlocker, which cannot handle large lists or become slow thereby.

The Pro++ is more aggressive than the Pro, it uses more aggressive sources like the badmojr Pro and through the extension, which is compiled for each list version individually from the known sources, more domains are added that fit the strictness level.
Furthermore, some trackers that restrict functionality have been excluded from whitelisting, such as `googletagmanager.com`

The Ultimate is even more aggressive.

**Comment by hagezi** [comment]
I have looked at this again and will unblock weebly.com in all lists.

**Comment by hagezi** [comment]
fixed.
