### ISSUE TITLE
Can’t like and follow anyone on TikTok

### ISSUE THREAD

**Issue by ECHLN** [hagezi/dns-blocklists#2083]
### Which AdBlocker/DNS cloud service do you use?

AdGuard DNS

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### With which block list(s) does the problem occur?

Multi ULTIMATE

### Which domain(s) should be unblocked?

TikTok 

### Why should the domain(s) be unblocked?

I keep getting an “Covert from NSData to NSDictionary failed” error message when trying to follow someone back on TikTok and I also can’t like videos

**Comment by hagezi** [comment]
@ECHLN The data octopus Tiktok again. I cannot reproduce the behaviour in the iOS app.

Unblock *.tiktokv.com, perform the action, remove *.tiktokv.com from the Allowlist and try again with blocked trackers.

**Comment by ECHLN** [comment]
This worked, thank you

**Comment by purple-emily** [comment]
@hagezi 
I know this issue is closed but this is affecting me. I’m using the TikTok fingerprinting list:

https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/native.tiktok.txt

I disabled it and can see user profiles again. Had to restart my iPhone to get the DNS cache to reset on my phone. 

I can’t exactly figure out which domain is causing the issue.

**Comment by purple-emily** [comment]
@hagezi what you said about disabling and then re-enabling has worked. I’ll try and keep an eye on my query logs and see if I can narrow it down. 

I came to the same conclusion as you. There was a few domains that matched that glob exactly.
