### ISSUE TITLE
Some google tracking domains

### ISSUE THREAD

**Issue by lthedetective** [hagezi/dns-blocklists#209]
userlocation.googleapis.com  (1 hosts pro)
gellar-pa.googleapis.com (1hosts)
firebaseinstallations.googleapis.com

**Comment by hagezi** [comment]
Hi,

thanks, they are already blocked in the ultimate version of my list, in the other versions they are not included. The reason is that blocking them restricts functionality.

`userlocation.googleapis.com`: Prevents the ability to share your location if you want to
`firebaseinstallations.googleapis.com`: Breaks some Firebase based apps, needed for Googles Cloud messaging
`geller-pa.googleapis.com`: Needed Google Assistant

Greeting,
Gerd

**Comment by lthedetective** [comment]
Oh thanks for the explanation

**Comment by hagezi** [comment]
The Pro Plus is designed to be just aggressive enough without limiting broadly used features. Therefore, these domains are not on this list.

I could include them and that might fit for you, but most likely not for the masses. One of the reasons why there is an Ultimate version.

You have the option to switch to Ultimate, or add the doamins to your personal blocklist, or add a list that blocks these domains.
