### ISSUE TITLE
DNS Blocklist for all Mastodon sites

### ISSUE THREAD

**Issue by KieranP** [hagezi/dns-blocklists#2136]
### Which domain(s) should be blocked?

All Mastodon sites. You can scrap lists such as https://instances.mastodon.xyz/ , https://instances.social/list , https://mastodonservers.net/ , etc

### Why should these domain(s) be blocked?

The majority of mastodon instances do not put content blocks in place or limit what other instances they are linked to. Which means that tag searches for "nsfw", "porn", "teen", etc, lead to 10,000s of unrestricted and unfiltered results for such content. They could be considered porn search engines. A DNS block list for all mastodon sites would be helpful.

**Comment by hagezi** [comment]
@sjhgvr Would this be something for your NSFW list or are they already covered?

**Comment by sjhgvr** [comment]
"**All** Mastodon sites should be blocked"
"**The majority** of mastodon instances .."

Anyways... Yes there are a lot of websites that have NSFW content (not as main content, but side content).
The oisd NSFW list however should be considered a list that if NSFW content is the main content (visible on the front page of the website) it'll be blocked.

So yes, if it's a mastadon instance with the main focus on NSFW, it should be in oisd NSFW, otherwise it belongs to the pile of websites that (if added to the list) a lot of people will report as FP to get it off the list instead.

I also like to keep things simple, oisd got 3 lists (small / big / nsfw)

@hagezi maybe a Mastadon blocklist is something for you?

**Comment by yoshimo** [comment]
I think this is going too far if part of a normal NSFW list. I don't want to block social media here that is a decentralised alternative to other platforms just because dedicated porn sites are blocked.
