### ISSUE TITLE
Yandex Ads

### ISSUE THREAD

**Issue by Alex67693** [hagezi/dns-blocklists#2343]
### Which domain(s) should be blocked?

https://strm.yandex.ru

strm.yandex.net

### Why should these domain(s) be blocked?

Display ads on modded game websites like ```https://www.playmods.net/apps/microsoft-powerpoint-mod/com.microsoft.office.powerpoint11/download```

**Comment by hagezi** [comment]
@Alex67693 
I don't see any calls to `strm.yandex.ru` in my region on the page. The ads are loaded via the following script, which can only be blocked with browser content blockers, not via DNS:

`<script src="https://yandex.ru/ads/system/context.js" async=""></script>`

I can't block `strm.yandex.ru` either because of the linked issues.

**Comment by hagezi** [comment]
@Alex67693 I have opened the page with Chrome, I can now see the strm calls, I'll see if this can be solved by blocking subdomains.

**Comment by hagezi** [comment]
@Alex67693 No, the ads cannot be reliably blocked via DNS. Even by blocking strm, they are sometimes loaded via the script.

**Comment by georgij-spiridonov** [comment]
Before filing an issue, you should actually check the previous issues. It was previously requested to unblock this domain, as it is used by the Yandex streaming service - Kinopoisk
