### ISSUE TITLE
Source Suggestion

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#2352]
https://github.com/ravenastar-js/shortlinks-scams

Translated from README.md:
"BLOCKLIST OF SHORT LINKS COMMONLY SENT BY SCAMMER ON DISCORD - PROTECT YOURSELF FROM PHISHING / SCAM (SCAMS)"

Edit:
See also https://github.com/Discord-AntiScam/scam-links
"This is a comprehensive repository with over 24000 curated phishing and scam domains that appear on the Discord platform."

**Comment by hagezi** [comment]
Thanks @jarelllama, but I'm actually fed up with cobbled together lists that you have to spend hours analysing and then realise that 80% of the domains are dead and the rest are just bloating your list because they'll be offline after a few days anyway. Some of them are also a false positive machine.

I just took a quick look. When I feel like it and have time, I'll do a few spot checks.

**Comment by hagezi** [comment]
https://raw.githubusercontent.com/Discord-AntiScam/scam-links/main/list.txt

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/a7c8f64a-71b8-4ac0-86b0-04f7f5b37716)

400 domains checked 335 dead, you already know how the overall check ends ...

I'm going to close ...

**Comment by hagezi** [comment]
![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/71c48ba0-f261-4491-8944-7017ec8b1d2a)

**Comment by jarelllama** [comment]
Thanks for checking @hagezi !
