### ISSUE TITLE
Whitelist domains update request

### ISSUE THREAD

**Issue by FadeMind** [hagezi/dns-blocklists#239]
Hello @hagezi please consider merge following whitelist domains against common major issues in many places.

Some domains are required for properly working Anti-Adblock Scriptlets, payments, streaming etc. Others are required for properly work major functionality apps mobile.

gemius.pl and adocean.pl provides adverts in Polish language sites and anti adblock handled by Adguard or Ublock Origin self.

thumb.highdeliveryscdn.com and logo.clearbit.com are used by Speed Dial 2 browser extension.

See also https://github.com/AdguardTeam/AdguardFilters/blob/master/BaseFilter/sections/foreign.txt

```
adocean.pl
adservice.google.com
adv.wp.pl
adx.adform.net
appsflyer.com
appsflyersdk.com
aria.microsoft.com
c.msn.com
cdn.optimizely.com
cdnjs.cloudflare.com
cm.g.doubleclick.net
crashlyticsreports-pa.googleapis.com
data.microsoft.com
data.msn.com
firebaselogging-pa.googleapis.com
gemius.pl
google-analytics.com
googleads.g.doubleclick.net
googleads.github.io
googleadservices.com
googletagmanager.com
googletagservices.com
graph.instagram.com
gstatic.com
gvt1.com
gvt2.com
gvt3.com
i.instagram.com
imasdk.googleapis.com
insideruser.microsoft.com
ironsrc.mobi
js.media-lab.ai
jsc.adskeeper.com
liftoff.io
logo.clearbit.com
moengage.com
moonactive.net
nest.com
onesignal.com
pagead2.googlesyndication.com
pubads.g.doubleclick.net
securepubads.g.doubleclick.net
smart.idmnet.pl
smartadserver.com
spectrum.net
ssacdn.com
static.doubleclick.net
static.hotjar.com
stats.g.doubleclick.net
thumb.highdeliveryscdn.com
v.fwmrm.net
www-google-analytics.l.google.com
www-googletagmanager.l.google.com
yo-digital.com
```

**Comment by hagezi** [comment]
Thanks, while skimming the list I noticed some popular trackers that are more for the personal whitelist if needed. 

Some of them are also on the whitelist in certain list versions.

I'll take a closer look at the list in the days to come.

**Comment by hagezi** [comment]
@FadeMind 

I took a closer look at your list, my comments on it, beware it follows a novel. ;)

The whitelisting of your mentioned domains may fit in the combination of DNS blocker together with browser content blocker. The content blocker then takes over what the DNS lets through. If the domains are blocked beforehand via DNS, the content blocker no longer comes into play.

However, my lists are pure DNS lists, which should protect the user even without content blocker. Therefore, I will not whitelist the Google Ads/Doubleclick domains, for example, because they are very popular and without content blocker lead to the fact that advertising is displayed on many pages. I have also not encountered any pages where blocking leads to problems. Exception is googletagmanager.com, which causes problems on some pages. There may be these pages, however, that can not be many. I can't unblock popular ads/tracker domains for the masses just because a handful of sites have problems with it. Such popular domains then belong on the personal whitelist.

As an example `google-analytics.com`, tracker rank 1, I know of a single site that does not play some videos due to blocking, `reuters.com`. But that's why I don't put it on the whitelist - the distribution is too big for that.
Different with `googletagmanager.com`, tracker place 2, blocking leads to problems on many sites. That is why it is unblocked in Light, Normal and Pro. In the Pro Plus and Ultimate still blocked and must be unblocked if necessary by the user himself.

Another example Firebaselogging/Crashlytics, one app does not start because they are blocked, absolutely bad app design. Should I unblock them for the masses because of this?

I tried to whitelist in my lists with sense and mind. They all have a certain strength, preferably without greatly restricting functions. Each list has been enhanced with its own extension in addition to the sources used. The Pro Plus for example is an attempt to find the perfect mix of Balanced and Aggressive.

Another important aspect: What had to be whitelisted yesterday because some functions were restricted, can be blocked again today because the whitelisting is invalidated by changes to the affected page. More than once experienced.

I'll take a closer look at your list and see if I need to whitelist anything. But this requires me to look at each domain and research what exactly restricts blocking. I would have preferred more details that are also testable.

**Comment by FadeMind** [comment]
@hagezi 

Please see also 
https://github.com/AdguardTeam/AdguardFilters/commit/3c7e702a70d8fde001e45234ca15eb95338360dd
https://github.com/notracking/hosts-blocklists-scripts/pull/9/files

**Comment by hagezi** [comment]
Thanks, may be Google/Doubleclick Ads/Analytics are causing problems in a handful of apps, but as mentioned above, I won't whitelist them for the masses. There are thousands of sites that have no problems with this. I also don't know of any DNS blocklist that has done this in its entirety.

**Comment by dnmTX** [comment]
@hagezi if `spectrum.net` is blocked here you can whitelist it. It's a Internet/TV/Phone provider and among other things,whoever using your list(s) will not be able to pay their bills.
And you can add `googletraveladservices.com` to your non-debatable list if you want 👍

**Comment by hagezi** [comment]
@dnmTX Thanks, only collector.pi.spectrum.net is blocked.

**Comment by hagezi** [comment]
@FadeMind 

Checked the rest of the list, some of the domains were already whitelisted, which I was able to check and additionally whitelisted:

```
# Needed for BBC iPlayer and BBC Sounds app (only Android TV)
mybbc-analytics.files.bbci.co.uk
mybbc-analytics.files.bbci.co.uk.edgekey.net

# Images in SpeedDial 2 Browser Extension
logo.clearbit.com
thumb.highdeliveryscdn.com
```

**Comment by azafrak** [comment]
Hello,

The dyson app's digital assistant gives an error when connecting. When I check it, hagezi is blocked by multi pro++. I think this is a false hindrance.

![9C0138D1-5E1F-441B-A38D-C08E428E2DEE](https://user-images.githubusercontent.com/30311445/214338473-8b24728e-6a01-41f0-a897-7a03377a4770.jpeg)
![58235F85-1A42-43FF-A773-58DEEB25FAC6](https://user-images.githubusercontent.com/30311445/214338496-e0a69e57-e333-44f4-96ab-dd4f88a83f63.jpeg)
