### ISSUE TITLE
Do you think it's possible to create a filter NSFW ?

### ISSUE THREAD

**Issue by BirdInFire** [hagezi/dns-blocklists#2416]
I would like to ask if it's possible to ass a list NSFW, like the one OISD do, but with the advanced quality of Hagezi's list ?

**Comment by MIOGMIOG** [comment]
Just use OISD NSFW filter.
I think it should be good enough.
If you think some domain or domains are missing, you can report it here - https://oisd.nl/nsfw_reporter

**Comment by hagezi** [comment]
Yes, the OISD NSFW is the best list available. I don't see what is qualitatively bad about it.
I see no reason to create a NSFW list, the other lists already do enough work.

If you have any suggestions for improvement, @sjhgvr is the right person to ask.

**Comment by BirdInFire** [comment]
> Yes, the OISD NSFW is the best list available. I don't see what is qualitatively bad about it. I see no reason to create a NSFW list, the other lists already do enough work.
> 
> If you have any suggestions for improvement, @sjhgvr is the right person to ask.

I was more thinking for in the future to have an ultimate + (who have every possible hagezi list) (for the deduplication you have).

but I completely understand your point I already use them (also have asked some other product to integrate them (example adguard in their NSFW API))

**Comment by BirdInFire** [comment]
maybe add them in the readme (for those who don't know them) something like at the very end, search for NSFW see "url"

**Comment by hagezi** [comment]
@BirdInFire There won't be an Ultimate+ with all the lists, it's far too big for GitHub and for most AdBlockers and that doesn't make any sense to me either. I have structured the lists in a modular way so that everyone can put together what they need.

Duplicates are not a problem, most of them have been outsourced to the individual lists - e.g. to the TIF - and at the latest when you add the lists to an AdBlocker, the few duplicates are sorted out.

The oisd NSFW is already mentioned here: https://github.com/hagezi/dns-blocklists/wiki/FAQ#whatshouldiuse

**Comment by hagezi** [comment]
I have added the oisd NSFW to the table of contents
:https://github.com/hagezi/dns-blocklists?tab=readme-ov-file#bookmark_tabs-table-of-contents

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/0ea6f951-84f5-4435-af7e-8af37e18f740)

**Comment by KnightmareVIIVIIXC** [comment]
[Steven Black's Porn List](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn-only/hosts)
