### ISSUE TITLE
New scam blocklist

### ISSUE THREAD

**Issue by jarelllama** [hagezi/dns-blocklists#2466]
Hi @hagezi I recently finished adding the last bit of features to my scam blocklist. I still want to wait a week of automated builds to see if there are any issues before I make an announcement on my repo. But in the mean time, I introduced a [light version](https://github.com/jarelllama/Scam-Blocklist#light-version) of my blocklist seeing how adding the now 30,000 domains from the original list would be impractical for most of your lists.

The light version currently has 2100 domains and I was hoping you could test it in your Ultimate list?

A quick rundown on the new features:
- Moved focus to identifying newly created scam sites instead of relying on manual reporting
- Alongside the Google Search API source, I've added additional public sources that I saw no one else has collated into a text format blocklist yet. For example, aa419.org, scamadviser.com, petscams.com, and more (only the actively updated sources are included in the light version). The list of sources I've integrated can be found [here](https://github.com/jarelllama/Scam-Blocklist/blob/main/SOURCES.md).
- Added automated parked domains removal (managed to remove 9% of domains from the full list on the first run)
- Added automated malicious NRD detection using [openSquat](https://github.com/atenreiro/opensquat) and [dnstwist](https://github.com/elceef/dnstwist). Both of which are open-source tools I have not seen any list maintainers integrate yet. Only dnstwist is used as a source for the light version because of it's near-to-none false positive rate. More about the two can be read in my [readme](https://github.com/jarelllama/Scam-Blocklist?tab=readme-ov-file#retrieving-malicious-nrds-using-automated-detection).

The light list, while a lot smaller than the full list, still meets my goal of collating scam domains as close to their registration date as possible. Hopefully this makes it a practical blocklist to include. I would love to hear your thoughts!

More about the new features and the light version can be found in my [readme](https://github.com/jarelllama/Scam-Blocklist).

**Comment by hagezi** [comment]
Great work!

I have optimised the size of the normal lists so that they can be used by all AdBlockers without losing effectiveness. The goal is <200000 "compressed domains". To achieve this, I have "moved" many malicious domains to the TIF medium and TIF, also to virtually eliminate duplicates between the normal and TIF lists. This does not mean that the normal lists no longer contain any TIF domains, but they do contain mainly Ads, Tracker, Telemetry and Analytics domains.

Some TIF sources vary greatly in size, sometimes from update to update, which makes it impossible to keep the normal lists stable in size. Furthermore, some domains are already dead before they even land on the list and thus inflate the lists unnecessarily. 

You have seen this with your scam list, for months there were < 10000 domains and suddenly there were > 30000 domains.

Everything has been reorganised so that the user can assemble what they need from the available lists in a modular way. I made the switch after the TIF list was available in almost all DNS cloud services. For AdBlockers that can't cope with the large TIF (e.g. AdGuard iOS), I created the smaller TIF medium so that every user is able to combine the normal lists with a TIF version.

Your Light version has an acceptable size today, so I could easily add it from Normal to Ultimate without exceeding the target of 200000 domains. But, will it stay that way? Probably not, this list will grow too, right?

I know that NextDNS users have the disadvantage of not being able to use the TIF version. Which for me would be the only reason to include your Light Scam version in the normal lists and not just in the TIFs. With all other services and self-hosting, the normal lists can be combined with a TIF version of your choice.
But if I start doing that, we'll soon have the huge lists from a few months ago again because there will be more requests as to why this and that source is not also included.
NextDNS doesn't want to include the TIF because they have their "own feeds" and, according to them, everything is covered. If that's the case, it shouldn't be a problem. I know it's not like that, but I don't organise my lists according to a single service.

I will add your Light to the TIF medium, the TIF will still contain the full version.

**Comment by sjhgvr** [comment]
@hagezi Thanks for the reminder, I've read this before (light list), but decided not to add it because I was already using these "full" lists:

https://raw.githubusercontent.com/jarelllama/Scam-Blocklist/main/adblock.txt
https://raw.githubusercontent.com/jarelllama/Scam-Blocklist/main/domains.txt

Seeing those are 404 now, I'll add the working ones 👍

**Comment by jarelllama** [comment]
my bad @sjhgvr for not tagging you in my updates in the repo

**Comment by hagezi** [comment]
@jarelllama As I said, after the next release the light will be included in the TIF medium and therefore also in the TIF. The TIF will continue to contain the full version. Size jumps are not a big problem in this version, unless the light "explodes".

@sjhgvr Thanks for your support.

**Comment by jarelllama** [comment]
Thanks everyone for the support 👍

**Comment by jarelllama** [comment]
Might as well tag @iam-py-test and @bongochong here to update them

**Comment by hagezi** [comment]
@sjhgvr @jarelllama 

I have adjusted my recommendations in this regard.

![grafik](https://github.com/hagezi/dns-blocklists/assets/104343908/da1f51d2-8b3d-4227-bd24-92f0c9dc5892)

https://github.com/hagezi/dns-blocklists/wiki/FAQ#whatshouldiuse

**Comment by jarelllama** [comment]
great work as always @hagezi
