### ISSUE TITLE
Oracle Cloud Console Telemetry

### ISSUE THREAD

**Issue by 4d62ext** [hagezi/dns-blocklists#2487]
### Which domain(s) should be blocked?

console-telemetry.oci.oraclecloud.com
console-telemetry.ca-montreal-1.oci.oraclecloud.com
console-telemetry.us-phoenix-1.oci.oraclecloud.com
console-telemetry.us-chicago-1.oci.oraclecloud.com
console-telemetry.ap-sydney-1.oci.oraclecloud.com
console-telemetry.ap-melbourne-1.oci.oraclecloud.com
console-telemetry.sa-saopaulo-1.oci.oraclecloud.com
console-telemetry.sa-vinhedo-1.oci.oraclecloud.com
console-telemetry.ca-toronto-1.oci.oraclecloud.com
console-telemetry.sa-santiago-1.oci.oraclecloud.com
console-telemetry.sa-valparaiso-1.oci.oraclecloud.com
console-telemetry.sa-bogota-1.oci.oraclecloud.com
console-telemetry.eu-paris-1.oci.oraclecloud.com
console-telemetry.eu-marseille-1.oci.oraclecloud.com
console-telemetry.eu-frankfurt-1.oci.oraclecloud.com
console-telemetry.ap-hyderabad-1.oci.oraclecloud.com
console-telemetry.ap-mumbai-1.oci.oraclecloud.com
console-telemetry.il-jerusalem-1.oci.oraclecloud.com
console-telemetry.eu-milan-1.oci.oraclecloud.com
console-telemetry.ap-osaka-1.oci.oraclecloud.com
console-telemetry.ap-tokyo-1.oci.oraclecloud.com
console-telemetry.mx-queretaro-1.oci.oraclecloud.com
console-telemetry.mx-monterrey-1.oci.oraclecloud.com
console-telemetry.eu-amsterdam-1.oci.oraclecloud.com
console-telemetry.me-jeddah-1.oci.oraclecloud.com
console-telemetry.ap-singapore-1.oci.oraclecloud.com
console-telemetry.af-johannesburg-1.oci.oraclecloud.com
console-telemetry.ap-seoul-1.oci.oraclecloud.com
console-telemetry.ap-chuncheon-1.oci.oraclecloud.com
console-telemetry.eu-madrid-1.oci.oraclecloud.com
console-telemetry.eu-stockholm-1.oci.oraclecloud.com
console-telemetry.eu-zurich-1.oci.oraclecloud.com
console-telemetry.me-abudhabi-1.oci.oraclecloud.com
console-telemetry.me-dubai-1.oci.oraclecloud.com
console-telemetry.uk-london-1.oci.oraclecloud.com
console-telemetry.uk-cardiff-1.oci.oraclecloud.com
console-telemetry.us-ashburn-1.oci.oraclecloud.com
console-telemetry.us-sanjose-1.oci.oraclecloud.com

### Why should these domain(s) be blocked?

Oracle Cloud console telemetry URLs

**Comment by hagezi** [comment]
https://github.com/hagezi/dns-blocklists/issues/68

**Comment by hagezi** [comment]
@RainmakerRaw

**Comment by RainmakerRaw** [comment]
Thanks for the ping, Gerd/@hagezi. I can concur that the stats page now loads fine with those domains blocked. Oracle recently overhauled the webUI and made some changes to the backend, authentication systems etc. I have just tested with `||console-telemetry.*oraclecloud.com^` and (after clearing the DNS and browser caches, of course) everything still seems to work. It seems Oracle have split off the desirable stats reporting into multiple subdomains and CNAMES now, including: 

```
telemetry.uk-london-1.oraclecloud.com
telemetry.uk-london-1.oci.oraclecloud.com
logging.uk-london-1.oci.oraclecloud.com
```

so I think it's safe to add a rule similar to the one I tested to the blocklist. We could always review if things change? 

Please note that I added the wildcard to cover all possible geographic location names, but also used it to omit the `.oci.`, allowing the rule to work on subdomains with and without that part. Some of the CNAMES and related domains omit that section. For example you can see in the first telemetry links above that one includes `.oci.` but the second (otherwise identical) domain omits it. While those particular domains are the 'desirable' ones, it's not unreasonable to assume that Oracle follow a similar pattern for the console-telemetry type URLs also.

**Comment by hagezi** [comment]
Many thanks for the details @RainmakerRaw .

**Comment by hagezi** [comment]
Most domains have no A-Record (dead), only the CNAME has one.

Example:
```
dig console-telemetry.af-johannesburg-1.oci.oraclecloud.com

; <<>> DiG 9.16.48-Debian <<>> console-telemetry.af-johannesburg-1.oci.oraclecloud.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 9461
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;console-telemetry.af-johannesburg-1.oci.oraclecloud.com. IN A

;; ANSWER SECTION:
console-telemetry.af-johannesburg-1.oci.oraclecloud.com. 900 IN CNAME overlay.af-johannesburg-1.oci.oraclecloud.com.
overlay.af-johannesburg-1.oci.oraclecloud.com. 900 IN A 129.149.64.209

;; Query time: 51 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Apr 09 11:36:06 CEST 2024
;; MSG SIZE  rcvd: 122
```

**Comment by hagezi** [comment]
I'll add them, but with the next automatic deadcheck they will be removed again if they don't have an A-record because they don't resolve via DNS anyway.
