### ISSUE TITLE
log16-normal-alisg.tiktokv.com

### ISSUE THREAD

**Issue by v1s7** [hagezi/dns-blocklists#2497]
### Which domain(s) should be blocked?

log16-normal-alisg.tiktokv.com

### Why should these domain(s) be blocked?

Similar "logXX-normal-alisg.tiktokv.com" domains are already blocked

**Comment by hagezi** [comment]
Hi, thanks, unblocked because:

```
# TikTok login after reinstalling the app (verfified on iOS)
log16-normal-*.tiktokv.com
```

**Comment by hagezi** [comment]
I'll have to take a closer look at this. I don't think all log16 domains had to be unblocked.

However, the log* domains are suspected of causing problems in the app. From time to time problems occur when following or displaying profiles. That's why they are currently only blocked in the aggressive lists. We never found out exactly which domain was causing the problem.

**Comment by hagezi** [comment]
I have checked this, log16-normal-*.tiktokv.com must be unblocked to log in after reinstalling on iOS.

**Comment by v1s7** [comment]
Thanks for a constructive and detailed answer. I'll try to research more extensively next time.

**Comment by hagezi** [comment]
No problem, with the data octopus Tiktok you never know, what is log16 today might be log22 tomorrow.
