### ISSUE TITLE
Sentry Documentation is blocked

### ISSUE THREAD

**Issue by salwinh** [hagezi/dns-blocklists#255]
https://docs.sentry.io/ is blocked and I believe it should be whitelisted

**Comment by hagezi** [comment]
Hi,

thanks, `sentry.io` is a "tracker".  Yes, opinions on this vary widely. But I also understand the opposite side.

That's why I unblocked the main domain only for the Light, Normal and Pro lists.

However, since the main domain `sentry.io` appears as a third party call in various page views without restricting its functionality, it remains fully blocked in the aggressive Pro Plus and Ultimate lists. Users of such lists expect such trackers to be blocked.

If you use an aggressive version, please whitelist sentry.io.

Kind Regards,
Gerd

**Comment by salwinh** [comment]
I'm using Normal, thank you for your work!
