### ISSUE TITLE
Unblock rewardtk.com and adscendmedia.com

### ISSUE THREAD

**Issue by lesar8** [hagezi/dns-blocklists#2626]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [X] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi LIGHT, Multi NORMAL, Multi PRO, Multi PRO mini, Multi PRO++, Multi PRO++ mini, Multi ULTIMATE, Multi ULTIMATE mini

### Which domain(s) should be unblocked?

rewardtk.com and adscendmedia.com

### Why should the domain(s) be unblocked?

- It's needed to redirect surveys and offers link from [Adscend Media](https://adscendmedia.com). They are a well-known companies that pay for taking surveys and offers.

- It's not malicious.

**Comment by hagezi** [comment]
@lesar8 Please provide link examples.

**Comment by hagezi** [comment]
`rewardtk.com` is categorised as a [referral domain](https://github.com/hagezi/dns-blocklists/wiki/FAQ#referral), as it is a pure link tracker (is only called up when a link is clicked), the domain will be unblocked.

https://urlscan.io/search/#page.url%3A%22rewardtk.com%22

Since I have not found a working link, I cannot judge why adscendmedia.com must also be allowed. @lesar8

**Comment by lesar8** [comment]
Hi, in order to do surveys/offers from them, one must need to create a profile first and verify email address by clicking on their link: 'http://adscendmedia.com/market-research/email/verification/,,,'. Since Hagezi blocked it, it's impossible to verify the account.

![Verify](https://github.com/hagezi/dns-blocklists/assets/133925958/549143f8-6d1a-4e61-b2d0-1e3e3483324a)
