### ISSUE TITLE
[False Positive] Yahoo Mail App

### ISSUE THREAD

**Issue by markangus2b** [hagezi/dns-blocklists#269]
I was setting up the Yahoo Mail app on a family members new Galaxy Tab A8 tablet and found Yahoo requires these domains to work properly on their Android app. I am using NextDNS on my Edgerouter. Blocking these two domains will result in a “Something went wrong” error message after clicking the sign-in button.

udc.yahoo.com
geo.yahoo.com

The next domain causes the same error message, but only when using Account keys to sign in by approving the login from another device.
pr.comet.yahoo.com

**Comment by hagezi** [comment]
Thanks for the advice, I already had another message from a user on Telegram yesterday. For web and iOS I had to whitelist other domains so the Yahoo app and using the mail account in Outlook worked. Crazy since they came from different sources, they seem to have changed something about the app or I'm sure it would have been noticed sooner.

The complete whitelist for Web/iOS and Android now looks like this:
```
consent.yahoo.com
geo.yahoo.com
guce.oath.com
m.yap.yahoo.com
pr.comet.yahoo.com
udc.yahoo.com
udcm.yahoo.com
```

ping sources:

`consent.yahoo.com` - @migueldemoura
* Was needed to show/confirm the cookie dialog on the web to get to the login screen. 

`geo.yahoo.com` - @adguardteam @alex-302 @anudeepnd @badmojr @bigdargon @bongochong @cats-team @d3ward @easylist @migueldemoura @notracking @sjhgvr @stevenblack @uniartisan @logroid @sjhgvr

* I think you should check again if the whitelisting of this domain is really necessary. It is already quite widespread. For web/iOS the whitelisting was not necessary. For Android apparently it is. Could someone test this again? I don't have any Android devices to test. Thanks!

`guce.oath.com` - @badmojr

* Was needed to get to the login screen in the app, login without whitelisting was not possible. Same for Outlook mobile app.

`m.yap.yahoo.com` - @anudeepnd @badmojr @bigdargon @bongochong @cats-team @d3ward @ookangzheng

* Not directly related to the Mail app, but needed for the Finance app, see below: https://github.com/AdguardTeam/AdguardFilters/issues/59810

`pr.comet.yahoo.com` - @adguardteam @alex-302 @badmojr @bigdargon @bongochong @cats-team @notracking @sjhgvr

* Needed for using Account keys to sign in by approving the login from another device.

`udc.yahoo.com` - @adguardteam @alex-302 @anudeepnd @badmojr @bigdargon @bongochong @cats-team @easylist @migueldemoura @sjhgvr @stevenblack @uniartisan

* “Something went wrong” error message after clicking the sign-in button in the Android App.

`udcm.yahoo.com` - @anudeepnd @badmojr

* “Something went wrong” error message after clicking the sign-in button in the iOS App. Cookie dialog does not appear.

In advance, thank you to all who are involved,
Gerd

**Comment by markangus2b** [comment]
I used my Galaxy S22 running Android 13  01/01/23 security patch level. I used the whitelisted domains you provided. I tried to sign-in with the following configuration on NextDNS

Blocklist
 ```
geo.yahoo.com
```
Allowlist
```
consent.yahoo.com
geo.yahoo.com
guce.oath.com
m.yap.yahoo.com
pr.comet.yahoo.com
udc.yahoo.com
udcm.yahoo.com
```

The results were the same. I click sign-in, type my username, click next and get the something went wrong error message.

I also tried the using the same configuration with the Outlook app and successfully logged in without any issues.

Thanks for resolving these issues quickly!

**Comment by hagezi** [comment]
@markangus2b Many thanks for testing.

**Comment by bongochong** [comment]
I'm not blocking `udc.yahoo.com` but thank you for the info about the 3 domains which I am blocking, @hagezi . Looking into all of this. Will probably take a while to figure it out, but in motion nonetheless.

**Comment by bongochong** [comment]
This should be mostly resolved in my standard lists, and completely resolved in my less aggressive Mini lists within an hour or two. Thanks again @hagezi. Always appreciate your thoroughness, and how you keep other projects + list maintainers in the loop.

**Comment by hagezi** [comment]
Many thanks @bongochong.

**Comment by bongochong** [comment]
Hey again @hagezi. I did some extra testing using a spare device running Android 10, and another spare device running Android 11. Methods of blocking included the local VPN route (AdAway and Rethink), along with two resolvers - via *private dns* - that block several of the domains in question (AdGuard and DNSWarden w/my larger list enabled). I performed a variety of actions using an old Yahoo account I've had for maybe two decades now, and I encountered no issues while using the Yahoo Mail application with `geo.yahoo.com` blocked. Every function of the application worked as expected with said domain blocked. I just removed it from the whitelist for the more lenient set of lists I maintain, as it is a known tracking domain so I'd rather keep it blocked on all fronts. I'm not sure, but perhaps the problems encountered by @markangus2b with this domain blocked have something to do with NextDNS in particular?

**Comment by hagezi** [comment]
@bongochong Thanks for testing. I also have no problems with blocked `geo.yahoo.com` on iOS. Maybe @markangus2b can test again.

**Comment by chillipal** [comment]
Just FYI:
 I use Pro Plus with NextDNS and noticed recently  ads showing up in Yahoo and AOL iOS mobile apps and traced that to the following host being not blocked:
m.yap.yahoo.com

The previous version of Pro Plus has yap.yahoo.com blocked that blocked all subdomains of yap.yahoo.com but the new update has these two: ads.yap.yahoo.com and ads-verify.yap.yahoo.com.

I have added yap.yahoo.com to my Denylist on nextdns. 
Also I never had any issue with geo.yahoo.com blocked in the past. I added it to my Denylist and no issues with Yahoo or AOL.

**Comment by hagezi** [comment]
Thanks @chillipal, will check the whitelisting of `m.yap.yahoo.com`.

**Comment by hagezi** [comment]
@chillipal Ich habe die Yahoo Finance App getestet, mit geblocktem m.yap.yahoo.com werden keine Nachrichtenin der App angezeigt. Entblockt man sie werden die News und zwischendurch Ads angezeigt. Beim erneuten Testen der Yahoo Mail App habe ich keine Einschränkungen festgestellt.
Ich werde die Domain für Light bis Pro entblockt lassen aber in Pro++ und Ultimate wieder blocken.

**Comment by hagezi** [comment]
@chillipal I have tested the Yahoo Finance app, with m.yap.yahoo.com blocked no news is displayed in the app. If you unblock it, the news and in between ads are displayed. When I retested the Yahoo Mail app I did not notice any restrictions.
I will leave the domain unblocked for Light to Pro but block it again in Pro++ and Ultimate.

**Comment by markangus2b** [comment]
I have done further testing and have confirmed what @bongochong thought. NextDNS is causing the issue.

I found that disabling the NextDNS Block Page feature on the Settings tab allows me to successfully sign into the Yahoo Mail app consistently with `geo.yahoo.com` and `udc.yahoo.com` on my Denylist.

I would guess that the reason for this behavior would be that the Yahoo app is looking up `geo.yahoo.com` and is instead being returned `blockpage.nextdns.io`.

During the same test I tried adding `pr.comet.yahoo.com` to my Denylist. Doing so still caused the app to error out when trying to setup "Account Keys". Loging in, along with other functionality seemed to be normal.

Now that I know NextDNS can cause these kinds of problems. I will have a separate configuration without any other NextDNS security services turned on to prevent this situation from happening again. I apricate everyone's time and effort in uncovering and resolving this issue. I will report this to NextDNS via the community forums.

**Comment by bigdargon** [comment]
@hagezi Sorry for the late reply! 2 domains `m.yap.yahoo.com` and `pr.comet.yahoo.com` for me cannot be removed, the reason these 2 domains are used to display ads in Yahoo applications.

Previously, I used MiTM to resolve HTTPS in Yahoo app (iOS), it contains ads so I need to block it!

@markangus2b You should leave the default configuration in the Settings tab, for me NextDNS works fine. Do not enable `Block Page` and `CNAME Flattening`.

![Screenshot 2023-01-31 091345](https://user-images.githubusercontent.com/10969626/215642704-2fd01892-5b1a-4faa-8264-ded791510c50.png)

**Comment by bigdargon** [comment]
Update: I used MiTM again to test.  In my opinion, still have to block `m.yap.yahoo.com` (because this domain contains ads), maybe remove `geo.yahoo.com` and `pr.comet.yahoo.com` (if it breaks the service)

![image](https://user-images.githubusercontent.com/10969626/215671370-068b0883-7359-4866-9800-82cecea5ca17.jpeg)

![image](https://user-images.githubusercontent.com/10969626/215671384-0cd1c179-a878-4df1-9d15-95b39ada0f8e.jpeg)

**Comment by hagezi** [comment]
Many thanks @bigdargon  ans @markangus2b .

I had not thought about the block page, this feature belongs banned from NextDNS. @romaincointepas

After all the back and forth and the test orgies, this leaves the following domains that need to be whitelisted for the Yahoo Mail app to work:

Login:
```
consent.yahoo.com
guce.oath.com

```
Only for setup Account Keys:

`pr.comet.yahoo.com
`

**Comment by Alex-302** [comment]
@bigdargon Hi. What the app is it https://github.com/hagezi/dns-blocklists/issues/269#issuecomment-1409771068?

**Comment by migueldemoura** [comment]
Didn't add a comment to this, but I also fixed this in my lists, thanks a bunch!

**Comment by bigdargon** [comment]
@Alex-302 Quantumult X https://apps.apple.com/vn/app/quantumult-x/id1443988620

![7E5F0BF1-937A-46E8-8ECB-C401F284A646](https://user-images.githubusercontent.com/10969626/215938071-445e7c4d-0507-44a6-875c-f219d2f3c759.png)

**Comment by hagezi** [comment]
I think we can close here, thanks again to all involved.

**Comment by notracking** [comment]
Thanks all, fixed it as well!
