### ISSUE TITLE
z-m-gateway.facebook.com

### ISSUE THREAD

**Issue by MagicalAlchemist** [hagezi/dns-blocklists#3130]
### Which domain(s) should be blocked?

z-m-gateway.facebook.com

### Why should these domain(s) be blocked?

Maybe new meta tracker domain? not sure but always pinging every 30 seconds nonstop on my father phone. This just appeared yesterday.

**Comment by hagezi** [comment]
It's unclear what this particular subdomain is used for, but it seems to be reltated to their "normal" data gateways, the CNAME is `dgw-mini.c10r.facebook.com`. I have not found any details about it.

**Comment by MagicalAlchemist** [comment]
> The whole of Facebook is a tracker ...

Agree, that's why im suspicious with this domain behaviour, from yesterday until now making call non-stop.

**Comment by hagezi** [comment]
@MagicalAlchemist I mainly have the CNAME in the logs. Seems to be used by the Facebook and Messenger app. Block the domain in your personal denylist and see what no longer works, or not.

**Comment by Retold3202** [comment]
I just took a look, and I *think* this is related to push/web notifications. 

[This](https://github.com/webcompat/web-bugs/issues/108139) issue seems to corroborate this, since there, we can see:

`wss://gateway.facebook.com/ws/realtime?x-dgw-appid=2220391788200892&x-dgw-appversion=0&x-dgw-authtype=1%3A0&x-dgw-version=5&x-dgw-uuid=9805546&x-dgw-tier=prod&x-dgw-app-stream-group=group1`

While this is specifically for `gateway.facebook.com`, `z-m-gateway.facebook.com` seems to be similar, and also CNAMEs to `dgw-mini.c10r.facebook.com`.

> The whole of Facebook is a tracker ...

💯

**Comment by hagezi** [comment]
Many Thanks @Retold3202
