### ISSUE TITLE
rony.lol

### ISSUE THREAD

**Issue by 4d62** [hagezi/dns-blocklists#3191]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Most Abused TLDs

### Which domain(s) should be unblocked?

rony.lol

### Why should the domain(s) be unblocked?

personal domain for a user  

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
I do not include every domain in the exclusions because I have to pay attention to the length of the denyallow modifier in the AdGuard lists. If they are too long, the rules become invalid. That's why I include popular domains or domains that restrict services, but not private sites that haven't been on any top list in the last 12 months.
These can be unblocked by the user.
