### ISSUE TITLE
gamingbeasts.com: Fake downloads, potentially malicious

### ISSUE THREAD

**Issue by cOnRiTCh** [hagezi/dns-blocklists#3247]
### Which domain(s) should be blocked?

https://gamingbeasts.com/

### Why should these domain(s) be blocked?

They have many fake downloads, and much of the content is likely very malicious. For example, there is `https://gamingbeasts.com/grand-theft-auto-6-download/ `which claims to offer a download of the video game Grand Theft Auto VI, a game that is far from being released. Additionally, it is very difficult to scan their downloads because the file sizes are massive. I cannot confirm whether there is actually malware, but I thought I should report it.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
https://www.virustotal.com/gui/domain/gamingbeasts.com/summary

**Comment by hagezi** [comment]
There are more such sites, and anyone who downloads from them must expect malware. Just like with APK pages. I had blocked a few of these sites and then there was a lot of shouting.

But I will block the domain because it has some flags and is blocked by a few Secure DNS. Furthermore, because this is definitely a fake.

Let's see how long it takes for the first one to scream - the site is on some top 1M lists.
