### ISSUE TITLE
Mozilla crash reporting domains blocked

### ISSUE THREAD

**Issue by bbhtt** [hagezi/dns-blocklists#3276]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

dnscrypt-proxy

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

```
crash-reports.mozilla.com
crash-stats.mozilla.org
```

### Why should the domain(s) be unblocked?

This breaks crash reporting to Mozilla

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by bbhtt** [comment]
https://github.com/hagezi/dns-blocklists/blob/main/wildcard/pro.txt

**Comment by hagezi** [comment]
I may move the domains to the aggressive lists. I think they are also used for the automatic sending of crash reports, which counts as bug tracking and is blocked from Pro onwards.

**Comment by bbhtt** [comment]
crash reports are never sent automatically.

**Comment by hagezi** [comment]
@retold3202

**Comment by hagezi** [comment]
If that's the case, I agree with you.

**Comment by hagezi** [comment]
Blocked:

```
crash-analysis.mozilla.com
crash-reports-xpsp2.mozilla.com
crash-reports-xpsp2s.mozilla.com
crash-reports.allizom.org
crash-reports.build.mozilla.org
crash-reports.maven.mozilla.org
crash-reports.mozilla.com
crash-reports.nightly.mozilla.org
crash-reports.security.mozilla.org
crash-reports.stage.mozilla.com
crash-stacks.mozilla.com
crash-stats-dev.allizom.org
crash-stats-django.allizom.org
crash-stats-django.mozilla.org
crash-stats-new-dev.allizom.org
crash-stats.allizom.org
crash-stats.mozilla.com
crash-stats.mozilla.org
crash-stats.stage.mozilla.com
crash.addons.mozilla.org
crash.mozilla.com
crash.planet.mozilla.org
crash.reporting.build.mozilla.org
crash.reporting.mozilla.org
crash.reporting.planet.mozilla.org
crash.reporting.svn.mozilla.org
crash.services.mozilla.com
crash.svn.mozilla.org
crash.vpn.mozilla.org
crashplan.addons.mozilla.org
crashplan.planet.mozilla.org
crashplan.svn.mozilla.org
crashplan.vpn.mozilla.org
crashstats.mozilla.com
```

CNAMES:
```
socorro.nonprod.webservices.mozgcp.net
socorro.prod.webservices.mozgcp.net
```

**Comment by hagezi** [comment]
The following blocked domains are on the Umbrella Top 1M list:

crash-reports.mozilla.com
antenna-prod.socorro.prod.webservices.mozgcp.net

Either there are a lot of users reporting crashes and the domain therefore ends up on the Top 1M list or it is triggered without user action.

**Comment by Retold3202** [comment]
> crash reports are never sent automatically.

@bbhtt This is incorrect, but I understand why you would come to that conclusion... Mozilla has not well documented this at all.

[According to a Mozilla employee](https://bugzilla.mozilla.org/show_bug.cgi?id=1593523):

> Having looked at the code again this does two things when checked:

> If you've got some old unsent crashes it sends them automatically w/o user interaction
> If a tab crashes it sends the crash report automatically w/o user interaction

(The pref being referred to here is enabled by default).

Therefore IMO these domains should be kept, and Mozilla really needs to improve their documentation around this.

**Comment by hagezi** [comment]
This also explains why the domain appears in the top lists. Since it is a mix of, I am moving it to the aggressive area.

**Comment by hagezi** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1593523
![grafik](https://github.com/user-attachments/assets/63fc97a2-05b5-4d16-bb1d-694813792fbc)

**Comment by Retold3202** [comment]
> How did you confirm this? This toggle was never enabled by default on any Firefox installation I've done in the past as far as I recall, and I just tested it by reinstalling Firefox; it's off by default.

Well... I stand corrected, apologies. I just tested myself and you're right, it doesn't appear to be enabled by default. I guess I just assumed it was since the other telemetry options are always automatically enabled...

> To me it seems quite clear that crash reporting requires user consent in one way or another. The default behavior is to prompt the user for their consent before reporting a crash, while the optional behavior is to do that automatically after the user enables it. I'm not sure it makes sense to block crash reporting if it is explicitly opt-in rather than opt-out.

IMO it's still worth blocking these domains (at least on the aggressive lists). It looks like even though automatic crash reporting is not enabled by default, Mozilla still promotes it & tries pushing users to enable it.

Example on mobile: 

![image](https://github.com/user-attachments/assets/8e052fe4-4af0-4e85-bb1e-ede3a0b596e3)

(In this case it actually does look toggled by default)

& An example on desktop:

![image](https://github.com/user-attachments/assets/825cfe1d-b27c-4525-a0bb-9c854e471b05)

I could see unsuspecting users enabling it without paying attention, which would add up with @hagezi seeing the domain on the top lists.

I feel like these domains would be best fit for the aggressive lists, since I would wager most people on the aggressive lists would never want this data to be sent.

**Comment by hagezi** [comment]
The domains are currently only blocked in Ultimate.

**Comment by Retold3202** [comment]
@rowboatz 

> As it stands, a user which makes a conscious and informed decision to either send a crash report once or allow the automatic sending of crash reports is completely blocked from doing so

I disagree - I think blocking it actually forces the user to make a conscious and informed decision whether they want to send these reports or not. If the user wishes to send these reports, rather than it being enabled for them (through dark patterns, by accident, or otherwise), they can make the active decision to whitelist the domains.

Also remember that these domains are only blocked on Ultimate as it stands (which IMO is the way to go), and I feel that this follows the current precedent for that list. If these domains are removed from Ultimate, you could also make the case to remove lots of other telemetry/crash reporting/etc domains. Where is the line drawn? That's where it gets very difficult. I feel like leaving them on Ultimate is the best course of action, and those who are fine with this type of data collection can either: 1. Make the conscious decision to send it through whitelisting the domains or 2. use a list less aggressive than Ultimate (Which they probably already are if they're fine sending this type of data).

> probably even without them being even aware of it (this is doubly problematic to me).

Since we're talking about Ultimate here, this would really only apply to those using the public DNS servers, but again: This type of data collection being blocked IMO is expected from Ultimate, so if someone is fine sending this type of data, they should just use a less aggressive list.

> If I understand correctly, the reasoning for blocking these domains is that irresponsible users should be protected from their own irresponsibility.

I don't think it's fair to characterize the concern here as solely irresponsibility, there are other factors to consider as well. For instance, in the past, [There was a bug that automatically sent tab crash reports to Mozilla without user knowledge](https://bugzilla.mozilla.org/show_bug.cgi?id=1424373). In general, a lot of things could happen, and those using Ultimate would likely expect to be protected from data collection in instances like this.

> I question whether this is what this blocklist aspires to do

I'm not Hagezi so I won't speak on his behalf, but my understanding is that Ultimate **does** aspire to block all data collection like this.

> Privacy violations on the web are usually invisible or severely deceptive, and therefore I think it is perfectly fair to try and shield end users from that. I don't believe this applies here.

I think I already touched on this above, but again, this is just far too subjective IMO. Under your criteria, I could already think of several domains off the top of my head that would also have to be removed. I don't think it's fair to decide what kind of data collection is or isn't acceptable for everyone with an aggressive list like Ultimate, it's too personal & subjective. It should be left to the user to decide & whitelist as they see fit.

> Blocking these domains basically means making decisions for the users, which I don't agree with philosophically.

I just see this as the complete opposite honestly - I feel like this is actually giving the decision *back* to the users vs. Mozilla or whoever else making it for them. I also think that again it fits the philosophy of Ultimate to block all forms of data collection of like this. 

> I think that this is a different situation from the question of whether automated crash reporting is enabled by default or not; in this case, the user is still asked for their consent. 

The box is checked by default... - again, I hate to keep coming back to this, but I can think of several domains that would also have to be reconsidered if they showed some kind of prompt but were still toggled by default. 

> That's a bold assumption in my view. For one, I use the aggressive lists and I would want this data to be sent.

I don't think it's a bold assumption to make at all, and if you're fine with this type of data being sent, I'd recommend either just whitelisting these domains or not using Ultimate, and instead stepping down to ex. Normal which doesn't block crash reporting like this.

> But even if it is true, I think the benefits are not worth the downsides, for the reasons I already layed out.

What exactly are the downsides of blocking these domains? Unless you're Mozilla, the only downside I can think of is it being slightly annoying to whitelist them if you actually want to send these reports (In which case you shouldn't be using Ultimate IMO).

Overall, I think your criteria is far too subjective for Ultimate. If we were talking about less aggressive lists, then I would be inclined to agree with you, but I don't think Ultimate should make opinionated decisions like this on what kinds of data collection are and aren't okay.

**Comment by Retold3202** [comment]
> Sorry for my rant and thanks for bearing with me! :)

No worries, you made some fair points yourself and it was nice to chat about it & hear your perspective :)
