### ISSUE TITLE
Potential trackers?

### ISSUE THREAD

**Issue by MEtICaRT** [hagezi/dns-blocklists#3364]
### Which domain(s) should be blocked?

sp-ao.shortpixel.ai
bstats.org

### Why should these domain(s) be blocked?

They are blocked by some filters on NextDNS but not by HaGeZi. Can you please check if they are actually trackers, and if they are, include them?

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
@MEtICaRT 

`sp-ao.shortpixel.ai` unblocked because images on various sites not loading. E. g, https://dynabook.com.my/

`bstats.org` - unblocked because https://github.com/hagezi/dns-blocklists/issues/1749
Can you name me pages where the domain `bstats.org` is called/triggered so that I can take a closer look?

**Comment by xRuffKez** [comment]
bstats.org is minecraft plugin mods telemetry, like mcstats.

**Comment by xRuffKez** [comment]
sp-ao.shortpixel.ai ~> ref
