### ISSUE TITLE
ublock.org

### ISSUE THREAD

**Issue by PedroHome18207** [hagezi/dns-blocklists#3502]
### Which AdBlocker/DNS cloud service do you use?

uBlock

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

ublock.org

### Why should the domain(s) be unblocked?

I know the history about this site, but I don't think it's necessary to block it, and also because "ublock.org" is commented on "uBlock₀ filters – Badware risks".

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by iam-py-test** [comment]
> "ublock.org" is commented on "uBlock₀ filters – Badware risks".

It is commented out because the uBlock Origin team instead opted for using a filter to force a warning onto ublock.org: https://github.com/uBlockOrigin/uAssets/commit/a9ebc6d9d4eb7b5bad9ca5172cda55ac4a3735ff
I don't remember the details of the internal discussion which led up to this decision, but I don't think there was any change in behaivor on behalf of ublock.org/Eyeo.
Thanks
