### ISSUE TITLE
Dynamic DNS domains list not useful with Pi-hole 

### ISSUE THREAD

**Issue by orazioedoardo** [hagezi/dns-blocklists#351]
AFAIK Pi-hole treats domains in blocklists as exact matches, i.e. _ddns.net_ matches _ddns.net_ but not _possiblymaliciousdomain.ddns.net_, which makes the [dyndns domains list](https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/dyndns.txt) not suitable for Pi-hole, and possibly other software too depending on how those treat domains.

**Comment by hagezi** [comment]
Yes, you are right.

The DynDNS domain/host list only fits for adblockers that support wildcard blocking. In Pihole you would have to create regex entries for this.
The known dangerous subdomains of the DynDNS providers are included in the TIF.

I now have two options:
1. remove Pihole from the ReadMe for this list.
2. add the known dangerous subdomains of the DynDNS providers to the domain/host version so that Pihole can do something with them. But you don't need this list in Pihole if you use the TIF.

Choose an option. ;)

Greetings,
Gerd

**Comment by orazioedoardo** [comment]
Option 1. As an alternative, the list in dnsmasq format can be used with Pi-hole (not through the UI though), as according to the dnsmasq man page `address=/domain/#` matches subdomains too.

> The domain specification works in the same way as for --server, with the additional facility that /#/ matches any domain.

https://man.archlinux.org/man/extra/dnsmasq/dnsmasq.8.en#S

> More specific domains take precedence over less specific domains, so: --server=/google.com/1.2.3.4 --server=/www.google.com/2.3.4.5 will send queries for google.com and gmail.google.com to 1.2.3.4, but www.google.com will go to 2.3.4.5

> Matching of domains is normally done on complete labels, so /google.com/ matches google.com and www.google.com but NOT supergoogle.com.

**Comment by hagezi** [comment]
Thanks, yes `address=/domain/#` matches subdomains in DNSmasq.

**Comment by hagezi** [comment]
Will remove the doamin and host version from the ReadMe, same goes for the badware hoster list.
