### ISSUE TITLE
fake and phishing websites

### ISSUE THREAD

**Issue by olumolu** [hagezi/dns-blocklists#3661]
### Which domain(s) should be blocked?

aces.gg
www.clg.gg
transaction.agency
www.fanzone.io
www.symbiont.io
toonily.net
www.contrafect.com
startdee.com
avif.io

### Why should these domain(s) be blocked?

It is said to be a comparison website but when you open it opens up multiple domain and some random website which does not seem to a genuine website to be in.
If you have time ki dly test your self and let me know what it does.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
This are gambling sites, blocked in the gambling list.

**Comment by olumolu** [comment]
How can i access this list with nextdns i want you to add this lists in pro+ and ultimate. So we can stay safe thanks

**Comment by hagezi** [comment]
@olumolu  The list is not available in NextDNS. The Gamblng lists used there are old. I will not restructure my lists just because a service does not block this or that. I will also not include domains in the normal lists that do not belong there just because a service does not maintain its lists. 
I can't save the whole world, the lists are available, NextDNS just has to use them.

You can see which of my lists are available in which service here:
https://github.com/hagezi/dns-blocklists/wiki/FAQ#availablelists
