### ISSUE TITLE
Bitdefender Antivirus detects Trojan in hosts file

### ISSUE THREAD

**Issue by kurtschlemmer** [hagezi/dns-blocklists#3795]
Hi there,
Bitdefender Antivirus detects Trojan.QHost.Gen. in hosts file and disinfects the file.
Do you have any solution for this?
Many Thanks

**Comment by xRuffKez** [comment]
In general, we are the wrong guys to ask for such kind of issues.

If the Hosts file is modified many Anti-Malware Solutions complain about infection. If you modified it yourself it's mostly a false alarm.

You can exclude/ignore this alarm.

We also do not recommend to use the hosts file because it creates high latency and system load. You might use YogaDNS or Technitium DNS for Windows for example.

If you can further questions, let me know. If not @hagezi will close this issue as not planned/wontfix
