### ISSUE TITLE
Samsung internet default home page blocked

### ISSUE THREAD

**Issue by user716253** [hagezi/dns-blocklists#3807]
### Which AdBlocker/DNS cloud service do you use?

ControlD

### ControlD users

- [X] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

quickaccess.internet.apps.samsung.com

### Why should the domain(s) be unblocked?

This is the default home page of samsung internet

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
The domain is not blocked, it is only blocked:
```
config-api.internet.apps.samsung.com
sia.internet.apps.samsung.com
www.internet.apps.samsung.com
```

ControlD seems to have a life of its own and truncates the `www` when parsing the lists and as a result `internet.apps.samsung.com` is completely blocked, not just `www.internet.apps.samsung.com`. This is only the case in ControlD and should not be the case.

A bug @yegors.

**Comment by hagezi** [comment]
@user716253 I will remove `www.internet.apps.samsung.com` until the bug in ControlD is fixed.

**Comment by yegors** [comment]
Hi,

We indeed strip out "www." from the domains and normalize the list as there are frequently 2 entries for many domains, ie: 

www.domain.com
domain.com

This saves quite a bit of memory, since all the lists we enforce have to exist in RAM on every DNS server. This is usually OK, but in scenarios like this, I see how it creates a problem. What's actually bad about "www.internet.apps.samsung.com", it appears to host a bunch of legal docs / ToS / privacy notices. 

Are there any other examples? We could make exceptions for certain filters not to strip out www when they're downloaded + parsed into a format we use.

**Comment by yegors** [comment]
Fair enough, we'll make an exception for the 3rd party filter parser. Will reply here when this is done.

**Comment by yegors** [comment]
Ops, forgot to mention - this is done now.
