### ISSUE TITLE
Videos are not being played and adblock is being detected

### ISSUE THREAD

**Issue by petergithubuser** [hagezi/dns-blocklists#3839]
Hello, I am using only hagezi multi normal list in NextDNS.io. So I am not using any adblock extension.

I am trying to watch videos in these brazilian websites, but they are detecting adblocks using hagezi multi normal list dns. I will paste the links and the printscreens. I dont know if it can be solved.  Perhaps the dns list is blocking elements of the pages below that prevent the video player of each of them work correctly. Thank you very much:

1) Adblock detected and paywall
https://www.gazetadopovo.com.br/ideias/educar-os-filhos-para-as-virtudes-pode-transformar-o-mundo/
https://www.gazetadopovo.com.br/republica/isencao-de-impostos-para-premiacoes-de-atletas-olimpicos-tem-apoio-amplo-na-camara-diz-deputado/
![image](https://github.com/user-attachments/assets/6309768b-60ef-4ef2-8467-638f59de1ef0)
![image](https://github.com/user-attachments/assets/56429a16-5adb-4f46-b28c-a03934bba275)

2) When go to these link, the first video player can not be played. The videoplayer is blocked.
https://www.terra.com.br/videos/
![image](https://github.com/user-attachments/assets/1a4a19a3-67b5-4183-b970-ea44da93762e)

3) Adblock detected. Not be able to play the video
https://www.sbt.com.br/ao-vivo
![image](https://github.com/user-attachments/assets/b62f4b88-048c-45fb-8bd5-d80703b89920)

4) Videoplayer always loads, but never play the video
https://noticias.uol.com.br/cotidiano/ultimas-noticias/2024/09/29/oitava-onda-de-calor-de-2024-sufoca-o-pais-sul-enfrenta-chuvas-intensas.htm
![image](https://github.com/user-attachments/assets/d3e56a4a-b9d3-4c20-840d-206ec6fea2ca)

5) Adblock detected. Not be able to play the video.
https://record.r7.com/fala-brasil/video/mc-ryan-desativa-redes-sociais-apos-aparecer-em-video-agredindo-a-ex-namorada-28092024/
![image](https://github.com/user-attachments/assets/7571f89f-0e64-4b38-a0d0-1bc952a0468c)

6) Not be able to play the video.
https://www.cnnbrasil.com.br/
![image](https://github.com/user-attachments/assets/99219fed-e34e-41b5-be12-f7c5ddf057bc)
![image](https://github.com/user-attachments/assets/f97d1d4c-c6d7-4dfa-b587-2648b7493ca2)

**Comment by hagezi** [comment]
@petergithubuser


1. https://www.gazetadopovo.com.br/ - As far as paywalls are concerned, I recommend switching from Normal to Pro - these are blocked in Pro if possible. Not in Normal, because this also prevents someone from buying a pass. With the Pro, I see no paywall and no AdBlock detection.

![grafik](https://github.com/user-attachments/assets/87041818-af23-4abd-8dca-1e4c5dcb46a5)

2.  https://www.terra.com.br/videos/ - I cannot reproduce this, the video can be played normally. Tested with the Pro list.

![grafik](https://github.com/user-attachments/assets/9056016f-28ca-4942-94b0-35deb802c899)

3. https://www.sbt.com.br/ao-vivo - Is geo blocked in my region, can't test it myself. I once asked in the cimmunity if someone can support, maybe you can also find out yourself what needs to be unblocked - If that is even necessary. A search has shown that `imasdk.googleapis.com` must be unblocked, but this domain is not blocked in any of my lists.

4. https://noticias.uol.com.br/ - I cannot reproduce this, the video can be played normally. Tested with the Pro list.

![grafik](https://github.com/user-attachments/assets/2148b798-b607-4506-8929-938fe378947c)

5. https://record.r7.com/ - requires the unblocking of `pagead2.googlesyndication.com`. This is definitely something for the **personal allowlist** as it is a popular ad domain that causes adverts to be displayed on other sites.

6. https://www.cnnbrasil.com.br/ - I cannot reproduce this, the video can be played normally. Tested with the Pro list.

![grafik](https://github.com/user-attachments/assets/5ecd8e7b-0ea0-4bf2-a4ac-ed22b35515c5)


Apart from 5, nothing is reproducible for me, so there is nothing I can do. There must be something on your side that is causing the problems, e.g.

- You are using additional blocklists, e.g. the NextDNS standard list
- You have activated the block page in NextDNS
- You are using stronger browser tracking protection than standard
- You use browser add-ons such as ad block or cookie consent block
- ...

I tested with Chrome desktop browser without add-ons and standard tracking protection.
