### ISSUE TITLE
Miscellaneous scam domains

### ISSUE THREAD

**Issue by IDKwhattoputhere** [hagezi/dns-blocklists#3879]
### Which domain(s) should be blocked?

`withyotta.com`
`rabbit.tech`
`distrochooser.snehit.dev`

### Why should these domain(s) be blocked?

1. https://www.youtube.com/watch?v=bBUkajbg688

2. https://www.youtube.com/watch?v=NPOHf20slZg

3. Not really a scam, prank distrochooser.de clone making you waste your time

Ever considered adding Scientology as a scam?
https://en.wikipedia.org/wiki/Scientology#Controversies
Lots of domains are here (missing some https://github.com/DandelionSprout/adfilt/issues/1061): https://github.com/DandelionSprout/adfilt/blob/83fc361414957999ec4c6c5f81ec6b2f1715ec53/Sensitive%20lists/AntiPreacherList.txt#L228

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
> Ever considered adding Scientology as a scam?

I also have my opinion on Scientology, but it would be censorship to block this as a scam in a general list.

**Comment by DandelionSprout** [comment]
My personal understanding is that anti-scam lists intended for large audiences, have a fairly strict definition of what counts as scam. The usual definition(s) are that the site will either:
1) Steal your money.
2) Try to get you to subscribe to very bad browser notifications or to install very fraudulent browser extensions.
3) Make your CPU extremely slow (whether by miners or otherwise).
4) Placing malware directly on your PC.

Sites that do none of those 4 are usually a "No deal" for anti-malware lists that aim to be included in adblocker extensions/softwares. <i>At most</i>, a note could be under the list's subscription that'd say something like <i>"! Users who want to also block [unusual topic], can check out [the list's link]."</i>
