### ISSUE TITLE
fake rustdesk website spam

### ISSUE THREAD

**Issue by olumolu** [hagezi/dns-blocklists#4009]
### Which domain(s) should be blocked?

rustdesk.secure-box.de
https://rustdesk.io/

### Why should these domain(s) be blocked?

Rustdesk.io and other websites spreading rustdesk software.

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
See also: https://github.com/rustdesk/rustdesk/discussions/9679

**Comment by olumolu** [comment]
https://rustdesk.co.nz/
@hagezi i think you missed this domain

**Comment by hagezi** [comment]
added:
```
rustdesk.co.nz
rustdesk.io
rustdesk.pl
rustdesk.secure-box.de
```
Ping @jobcentertycoon

**Comment by ashrafru** [comment]
Hello @hagezi — requesting a review of rustdesk.co.nz only, not the other domains in this report.

I'm the owner. The domain has been registered to ASH NET Limited, a New Zealand ISP and managed IT provider, since 15 November 2022 — same registrant throughout, no change of hands. Company site: https://ashnet.co.nz, phone 09 269 4000. It was added to this issue in a comment listing it alongside rustdesk.io, rustdesk.pl and rustdesk.secure-box.de, and as far as I can tell it was included by name rather than after a look at what it serves.

What it serves today: it is our remote-support download page for our own customers. Every download link points directly at the official RustDesk release assets on https://github.com/rustdesk/rustdesk/releases — nothing is rehosted, repackaged or modified, and no binary is served from our server. The footer states that RustDesk is AGPL-3.0 software and that ASH NET is not affiliated with the RustDesk project, with a link to the upstream repository. There is an anti-fraud notice telling customers we never cold-call them to install remote-access software and never ask for banking logins or passwords during a session. It runs on our own hosting alongside our other company domains, under a Let's Encrypt certificate issued for rustdesk.co.nz.

I do understand why RustDesk-named domains get caution — the tech-support scam pattern is real and I'd rather the list err that way. So I'm asking for a look at the page rather than assuming a mistake.

If the listing can't be lifted while the domain carries the RustDesk name, I'd rather hear that plainly so we can move the page to a hostname under ashnet.co.nz. And if there's a change that would satisfy you — a prominent "unofficial, operated by ASH NET Limited" banner at the top, clearer company identification, anything else — say so and I'll make it.

Cross-reference: uBlockOrigin/uAssets#34560

Thanks for the work you put into these lists.

**Comment by hagezi** [comment]
Thanks @ashrafru, will be removed.

**Comment by iam-py-test** [comment]
Fixed in my list as well. Sorry for the delay.
