### ISSUE TITLE
Proxy sites

### ISSUE THREAD

**Issue by Bismuthfallacy** [hagezi/dns-blocklists#4052]
### Which domain(s) should be blocked?

readandmath.today
Omegaproxy.com
Anonymous.at
Onlineanonymizer.com
Proxy.cc
Unblocksites.org
Free-webproxy.com
Surfskip.com
Limitlessproxy.com
Unrestricter.com
Anonymizing.com
Unblockmate.com
Fireprox.net
Unrestricter.org
Proxyforfree.eu

### Why should these domain(s) be blocked?

They allow bypassing enforced DNS.

Really appreciate what you do, but wonder if you might share how you find new sites to update your list with? Is AI involved? I only ask because these sites listed were listed on Bing search results and I know it’s a mammoth task keeping up with all of them, but wonder if you use AI to scan search results for ‘free web proxy’ or something?

Thank you

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
Only a few proxies are included, adding all possible ones would probably make the list too big.  I am not looking for proxies. I am not looking for proxies. The main focus is on VPN/DoH/...

**Comment by Bismuthfallacy** [comment]
> Only a few proxies are included, adding all possible ones would probably make the list too big. I am not looking for proxies. The main focus is on VPN/DoH/...

Ah ok, why is this?

thank you

**Comment by hagezi** [comment]
There are so many proxies that you can't keep up with adding them, and the list would be too big. There used to be an issue about this here, but I can't find it now, it was also about a huge list of proxies.

That makes no sense, there is always a bypass if you want. The easiest way is via DoH, instead of using https://dns.quad9.net/dns-query, you simply use http://9.9.9.9/dns-query and the DNS is bypassed, even if dns.quad9.net is blocked.

The list is more for catching the worst and preventing apps from getting rid of their tracking data via DoH.
