### ISSUE TITLE
amazon video domain that should be allowed

### ISSUE THREAD

**Issue by jordansworld** [hagezi/dns-blocklists#4202]
### Which AdBlocker/DNS cloud service do you use?

AdGuard

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO++

### Which domain(s) should be unblocked?

api.us-east-1.aiv-delivery.net

### Why should the domain(s) be unblocked?

not ad or tracker

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by hagezi** [comment]
You're wrong again ... this blocks video telemetry.

Please don't just post any issue because you think it doesn't belong on the list. If it leads to restrictions, I'll take a look at it. But this domain does not lead to restrictions.

Sorry, but I already have enough work with the lists. Believe me, I've worked intensively on what I block and what I don't block.

The Pro++ or my lists in general might not be the right lists for you.
