### ISSUE TITLE
Azure Artifacts blob storage should not be on block list

### ISSUE THREAD

**Issue by djtinklenberg** [hagezi/dns-blocklists#4232]
### Which AdBlocker/DNS cloud service do you use?

Pi-hole

### ControlD users

- [ ] IMPORTANT - I assure that I have not set the Block Response in ControlD to Custom or Branded and can confirm that the problem still occurs.

### NextDNS users

- [ ] IMPORTANT - I can assure that I disabled the block page in NextDNS and can confirm that the problem still occurs.

### With which block list(s) does the problem occur?

Multi PRO

### Which domain(s) should be unblocked?

1oavsblobprodcus350.blob.core.windows.net
37bvsblobprodcus311.blob.core.windows.net

### Why should the domain(s) be unblocked?

Azure Artifacts uses Azure blob storage accounts to store NuGet packages in; these two domains are used for such purposes. When running Pi-hole with the Multi PRO blocklist, developers will be unable to restore NuGet packages and therefore build their software projects if the project's NuGet packages end up being kept in one of the two storage accounts listed. This storage mechanism is abstracted and cannot be controlled by organizations or developers (i.e. organizations have no control over which storage accounts Azure Artifacts uses to store NuGet packages).

### Privacy

- [X] I confirm that the report does not contain any private information.

**Comment by bongochong** [comment]
As usual, thank you for pinging me @hagezi! Unfortunately, these domains have long been associated with Windows telemetry (via Safer-Networking, CrazyMax, and a few other sources), so I will have to do some digging before I make a final decision.

What I will likely end up doing is leaving the two domains in question blacklisted in my default lists, while whitelisting them from my light / mini lists, since -- as the user who filed this issue has noticed -- blocking them has been associated with breakage in some contexts (though this is the first time I've been alerted to it regarding these domains in around a year).

I will also be adding the domains, with annotations, to [this small list of potentially problematic blocks associated with Microsoft telemetry](https://github.com/bongochong/CombinedPrivacyBlockLists/blob/master/WindowsTelemetryBlockSupplements/PPD-AWT.txt), after an overdue update of my Windows Telemetry Block List supplements later today.

**Comment by bongochong** [comment]
Good to know @hagezi! The last time I worked as a SysAdmin in a predominantly Windows environment was 2015/16, and I seldom boot into the OS on my personal machines these days (except to occasionally work in Lazarus, or for gigs that require it). So it's very useful to hear this from you first hand, as opposed to doing the usual forum digging and testing myself. Maybe I will just whitelist the domains from both lists when updating everything later.

**Comment by djtinklenberg** [comment]
> Thanks @bongochong I don't think it's telemetry. Just randomly generated subdomains. I don't see a call to these domains even in a network with several 100 Windows PCs.
> 
> Yes, they come from the WindowsSpyBlocker list, but this contains lots of domains that have nothing to do with telemetry or tracking.
> 
> I haven't found any proof either. But maybe I'm completely wrong.
> 
> @djtinklenberg What problems exactly did the domain blocking cause?

@hagezi The domain blocking prevents developers from being able to download the NuGet packages stored via their organization's [Azure Artifacts](https://azure.microsoft.com/en-us/products/devops/artifacts/) NuGet feed. Without being able to download these packages, I am unable to build/compile software projects for work.

If it provides any additional context, I will say these domains are unlikely to be related to telemetry as it's the domain pattern for [Azure Blob Storage](https://azure.microsoft.com/en-us/products/storage/blobs/), which are just general purpose accounts for storing unstructured data, and the pattern for these storage accounts is **[account name].blob.core.windows.net**. As you alluded to above, I believe the two particular subdomains listed in the issue are randomly generated names for the backing storage accounts Azure Artifacts evidently uses under the hood. I don't suppose there's any history involved that could point to why these domains ended up on the list in the first place?
