### ISSUE TITLE
what about when you passed away?

### ISSUE THREAD

**Issue by muhasturk** [hagezi/dns-blocklists#4256]
the work that has been done is very valuable, have you thought of an heir so that it does not remain unmaintained?

**Comment by Shura23** [comment]
> 已经完成的工作非常有价值，您是否想过一个继承人，这样它就不会无人维护？

You're kind of cursing others. I'm not sure if there's a mistake in the browser's translation. The browser translates your words as death, which means when the developer dies.

**Comment by Shura23** [comment]
I'd like developers to explain how to use the project, for example, if I want to open a branch, how to add a whitelist or blacklist, and where to change it. Hopefully there will be a document on the use of the project

**Comment by hagezi** [comment]
I haven't thought about that yet, but when the time comes, I certainly will.

**Comment by Shura23** [comment]
> I haven't thought about that yet, but when the time comes, I certainly will. They are just DNS blocklists ...

I wish there was a detailed documentation, I wish there was a branch, but I don't know how to use your project. I would like to explain where to add whitelist or blacklist, how to remove dead and duplicate domain names, etc. I don't know how to use your project since it doesn't have an introduction to this

**Comment by Shura23** [comment]
> I haven't thought about that yet, but when the time comes, I certainly will. They are just DNS blocklists ...

I wish there was a detailed documentation, I wish there was a branch, but I don't know how to use your project. I would like to explain where to add whitelist or blacklist, how to remove dead and duplicate domain names, etc. I don't know how to use your project since it doesn't have an introduction to this
