### ISSUE TITLE
The Minefield of Google Ads

### ISSUE THREAD

**Issue by HellboyPI** [hagezi/dns-blocklists#591]
I just saw this video:
https://www.youtube.com/watch?v=vL4uk3FjubQ

That kept me thinking.
In your lists affiliate domains are allowed. Does this mean that Google Ads links in Google Search are also allowed?

**Comment by hagezi** [comment]
Yes, not new and a hot topic. Because you can't hide these ads in Google search via DNS, referral domains are allowed, except in the Ultimate version. What you can do via DNS is to block the referenced "fake pages".

DNS blocker offer a good protection of privacy by blocking tracking, metrics and telemetry. They can be used to block the vast majority of ads, malware, scam, fake and co, but not everything can be blocked at the DNS level!
Therefore, I additionally recommend the use of a browser content blocker.
These also hide ads in the search results.

Recommendation: https://github.com/yokoffing/NextDNS-Config#what-browser-should-i-use-that-has-adblocking

Google must react here. Another reason not to use Google as a search engine.

**Comment by nezlobnyj** [comment]
@hagezi What would be your recommendation if not Google? I've heard nice things about Startpage for instance as being "anonymised" Google wrapper. What about others like Brave or Qwant?

Tried DuckDuckGo but they were vastly inferior in quality of results even if compared with non-personal Google results.

Thanks

**Comment by hagezi** [comment]
I use DuckDuckGo, but the search results are indeed not the best. If you want "Google search results" Startpage is probably the best choice.

**Comment by AAraonWPaul** [comment]
> I use DuckDuckGo, but the search results are indeed not the best. If you want "Google search results" Startpage is probably the best choice.

Or searx.. or mojeek. Not trusting an ad company despite what they say.
