### ISSUE TITLE
[Dynamic DNS/Free Hoster] additional domains to add

### ISSUE THREAD

**Issue by dnmTX** [hagezi/dns-blocklists#60]
@hagezi i had my own personal Dynamic DNS list that i was using so i compared them and excluding the duplicates there were few left if you want to add them to yours:
```
22web.org
66ghz.com
cloudwaysapps.com
ddnslive.com
dynadot.com
dynamic-dns.net
gtempurl.com
hyperphp.com
jimdofree.com
myjino.ru
preview-domain.com
swtest.ru
weebly.com
xsph.ru
```
Cheers 👍

**Comment by hagezi** [comment]
Hi,

Thank you very much, I will add them later.

Greetings,
Gerd

**Comment by hagezi** [comment]
Added, thanks for your support!

**Comment by dnmTX** [comment]
@HellboyPI because all of them(as far as i remember) are being abused.Spreading malware and such,the same way the Dynamyc Domains are used for. So that is why i add them at the time. All those(some of their URL's) were in phishing/malware blocklists.
Why treat them differently?

**Comment by HellboyPI** [comment]
Weebly & Jimdo offer free website creation, but only as subdomains.
Example:
mysite.jimdofree.com
mysite.weebly.com

In the past probably some of these free websites were (ab)used for malware/ phishing. And that's why they got blacklisted. The subdomains, not the whole domain.
Blocking the whole domain ensures that your network is always 100% protected, even if the subdomain changes.
I understand that. But, why are these domains on your dynamic dns blacklist? These free websites are hosted on Jimdo/ Weebly servers. Or not? 
These domains should be added to other list, not to dynamic dns list.

As for dynadot.com, does it offer a dynamic dns service on the dynadot.com domain? I can't find this information on their website.

**Comment by hagezi** [comment]
I understand both points of view, since it is a pure DynDNS list, weebly.com should not really be on the list. On the other hand, there are 1780 weebly.com subdomains on the TIF list. So weebly.com is definitely dangerous.
I am thinking about what to do with the list, I could expand it and rename it to "DynDNS + website hosters that are mostly dangerous" or remove the non-DynDNS domains.
I tend to expand the list. What do you think?

**Comment by HellboyPI** [comment]
3 options:

1) You wrote, that You found 1780 weebly.com subdomains on the TIF list. Based on that information (subdomains are already on that list), website hosters that are mostly dangerous should be put on the TIF list.

2) Create a separate list for website hosters, like You've done for Dynamic DNS. That way, users will decide whether to use that list. For users who want maximum protection, add this new list to the Pro.Plus list.

If a provider offers dynamic dns service and is a website hoster that is mostly dangerous, put the domain on both lists (Dynamic DNS and Website hosters).

3) Expand the Dynamic DNS list.


I'm leaning towards option 2.

**Comment by hagezi** [comment]
I also tend to 2., if I have time I look which hoster that would be at all, or does anyone have a list in his back pocket? ;)

**Comment by dnmTX** [comment]
> does anyone have a list in his back pocket?

start with the worst and will keep on adding them: `||000webhostapp.com^` 😉

**Comment by yokoffing** [comment]
> 1. You wrote, that You found 1780 weebly.com subdomains on the TIF list. Based on that information (subdomains are already on that list), website hosters that are mostly dangerous should be put on the TIF list.
> 
> 2. Create a separate list for website hosters, like You've done for Dynamic DNS. That way, users will decide whether to use that list. For users who want maximum protection, add this new list to the Pro.Plus list.

I naturally lean towards option 1, but this may break websites for average users.

I think option 2 is sensible. Including the `Dangerous Hosts` list (or whatever you end up calling it) automatically in Pro++ list is good, too.

You'll have to add another column [to your chart](https://github.com/hagezi/dns-blocklists#multi-blocklist-version-and-size-overview), @hagezi! 😆

**Comment by hagezi** [comment]
The first attempt:

https://github.com/hagezi/dns-blocklists/blob/main/domains/hoster.txt
https://github.com/hagezi/dns-blocklists/blob/main/adblock/hoster.txt

Feedback requested.

Thanks,
Gerd

**Comment by yokoffing** [comment]
Looks good to me 👍🏻

**Comment by hagezi** [comment]
No further feddback, so I'll close the issue.
