### ISSUE TITLE
ssl.1.media.ntvde.ndcaidemh.com and more - Ads before regulare videos at n-TV

### ISSUE THREAD

**Issue by JF62** [hagezi/dns-blocklists#720]
#### Which domain(s) should be blocked?

ssl.1.media.ntvde.ndcaidemh.com
ssl.2.media.ntvde.ndcaidemh.com
ssl.3.media.ntvde.ndcaidemh.com
and maybe more (4,5,...?)

#### Why should the domain(s) be blocked?

advertising videos before regular video starts

I use atm regular expression in pihole for and it works fine: (\.|^)media\.ntvde\.ndcaidemh\.com$

Would be nice, to have in pro-plus

**Comment by hagezi** [comment]
Thanks will test it again, I mean the blocking leads to that the livestream does not start if you also do not use a content blocker in the browser.

**Comment by JF62** [comment]
> Thanks will test it again, I mean the blocking leads to that the livestream does not start if you also do not use a content blocker in the browser.

Tested in Android without any blocker in browser and works fine. In chrome at windows you are right

**Comment by hagezi** [comment]
Yes, desktop browsers were the problem, I remember.

**Comment by JF62** [comment]
Do you see a chance? Should I investigate further?

**Comment by hagezi** [comment]
No, these are CNAMES for `damoh.schneevonmorgen.com` is used on tiny German sites for video advertising. Is completely whitelisted because the blocking leads to the fact that the videos can not be played. 
Blocking this at DNS level makes no sense, the blocking should be left to browser blockers like uBlock.
