### ISSUE TITLE
FP ip.istatmenus.app

### ISSUE THREAD

**Issue by RainmakerRaw** [hagezi/dns-blocklists#75]
Literally used to simply fetch the user's public IP on request, for display in the Network section of Bjango's paid iStat Menus app on macOS. Currently blocked in `pro.plus.txt`, breaking this functionality.  

[Domains contacted by iStat Menus](https://bjango.com/help/istatmenus6/domains/).

Please kindly consider whitelisting/removal. Thank you (again!).

**Comment by RainmakerRaw** [comment]
On investigation, it appears the FP originates with 1Hosts Pro again. I have filed reports with them before, but they have many outstanding Issues with no acknowledgement for quite some tme, unfortunately. That's how I actually found and started using your lists, and being thankful for your responsiveness! I'd recently been using 1Hosts Lite, NoTracking and Lightswitch05 (again too many FPs in time), after stepping 'up' from just OISD alone.  

Am I correct that your Pro list contains OISD full, 1Hosts Lite, NoTracking and AdGuard SDNS filter? I only ask, as the Pro.Plus states it also contains oisd.domains.txt, and the general format of the sources page is that only additions above the previous list level are included in the sources for that list (i.e. $previous_list.txt, $extra_list1, $extra_list2). 

This oisd.domains.txt being listed in both Pro and ProPlus breaks that pattern, so I wondered whether it (OISD full?) *is* actually included in Pro, and merely duplicated in the ProPlus source list; or is it rather listed accidentally in Pro's source list, and accurate as a new addition for ProPlus? I hope you understand my confusion, sorry I didn't explain better. 

I started off with using Pro, but a lot of Amazon ad domains made it through (FireTV) and Pro.Plus catches these. The FPs from upstream make me wonder whether Pro is sufficient after all, as it's otherwise a nicely balanced list. I used only OISD for a long while, but it lets through so much now I was starting to wish for more aggressive blocking and my personal blocklist was growing unwieldy versus simply stepping to another pre-made list. Thanks so much again, your dedication and responsiveness (kindness) is appreciated.

**Comment by hagezi** [comment]
@RainmakerRaw Thanks for your support!

Yes, the lists light to pro build on each other by including the upper list, the pro++ is different. It includes again all external upstream and other lists.
Why? So that I can e.g. whitelist domains in the lists light to pro, but do not have to do this for the pro++. The goal was to be able to handle the pro++ completely different. I could have done this differently but to be as flexible as possible I chose this way.
The finished lists do not contain any duplicates.

You said you are missing some things in the pro, e.g. Amazon doamins, can you tell me the missing ones?

If you want to contribute to the project with your blacklist or other input, very welcome, any help is appreciated.

Thanks and greetings,
Gerd

**Comment by RainmakerRaw** [comment]
Gerd,

Thanks so much for your helpful and welcoming reply. I'm sorry for the delay, I'm sick at the moment and not spending much time doing anything useful. I'll come back to you when I'm better placed to respond, but I didn't want to leave your message unanswered. 

Thanks again!

**Comment by hagezi** [comment]
@RainmakerRaw No problem, you in any case get well soon!
