### ISSUE TITLE
config.uca.cloud.unity3d.com

### ISSUE THREAD

**Issue by botthebestplayerintheworld** [hagezi/dns-blocklists#79]
https://github.com/badmojr/1Hosts/issues/844

**Comment by hagezi** [comment]
@botthebestplayerintheworld 

The domain is very common and present in many blocklists. It is used for in-game analytics and tracking. These analytics should actually be able to be turned off ingame. If blocking such a domain causes game functions to partially not work, this is definitely a very bad software design and should be seen as a bug of the game.

See: https://docs.unity3d.com/Manual/UnityAnalyticsDataPrivacy.html

Please understand that I don't whitelist these doamin for everyone just because something doesn't work in a single game. Contact the manufacturer or put them on your personal whitelist.

Kind regards,
Gerd
