### ISSUE TITLE
telegraph.co.uk

### ISSUE THREAD

**Issue by SeriousHoax** [hagezi/dns-blocklists#933]
#### What adblocker/DNS cloud service are you using?

Adguard Home with Hagezi Muti Pro++ and also tried ControlD with the same filter `https://freedns.controld.com/x-hagezi-proplus` in Chrome

#### Which blocklists are used?
Hagezi Muti Pro++

#### Which domain(s) should be unblocked?
I'm not sure which one but something loaded on this page: `https://www.telegraph.co.uk/business/2023/04/12/elon-musk-bbc-interview-vaccine-side-effects-cover-up/`

#### Why should the domain(s) be unblocked? If necessary, please describe the steps to reproduce.
When blocked, More stories section can't be viewed.

With Hagezi Multi Pro++:
![1](https://user-images.githubusercontent.com/29574622/232006504-cb921584-8afe-4049-8f2b-ca9e65feace8.png)

With Cloudflare DNS:
![2](https://user-images.githubusercontent.com/29574622/232006666-6e19243f-094e-4a23-a373-180359c9060f.png)

**Comment by hagezi** [comment]
Thanks, I'll have a look at it.

**Comment by hagezi** [comment]
A first check showed that you probably have to whitelist some popular trackers to display the widget. I'll have to take a closer look when I have time.

Even with the OISD the widget is not displayed and with the OISD almost everything works.

Should the whitelisting of popular trackers be necessary, this is definitely something for the personal whietlist. I will not whitelist these for the masses because a widget is not displayed on a page.

**Comment by hagezi** [comment]
If someone has the time and desire to do the further analysis, gladly.

**Comment by hagezi** [comment]
@SeriousHoax I have found an acceptable solution. The culprit is `cdn.petametrics.com`. It is a not so popular tracker used for chat, email messaging, customer support, and other interaction tools. It is enough to whitelist the CDN, all other subdomains can remain blocked. The tracker data is transmitted via `query.petametrics.com`, which remains blocked.

Details: https://whotracks.me/trackers/petametrics.html

I will whitelist the domain except for the Ultimate.
