### ISSUE TITLE
Unblock licensing.bitmovin.com

### ISSUE THREAD

**Issue by rapdodge** [hagezi/dns-blocklists#965]
### Which AdBlocker/DNS cloud service do you use?

AdGuard Home

### Which blocklist(s) do you use?

Multi ULTIMATE

### Which domain(s) should be unblocked?

licensing.bitmovin.com

### Why should the domain(s) be unblocked?

licensing.bitmovin.com are need for DRM player.

![image](https://user-images.githubusercontent.com/33513626/233819422-5a0296ca-478f-4718-b123-84e90cc30eed.png)

**Comment by hagezi** [comment]
Please provide sample links that I can use to check that there are functional limitations due to blocking.

**Comment by rapdodge** [comment]
> Please provide sample links that I can use to check that there are functional limitations due to blocking.

https://licensing.bitmovin.com/licensing

The payload are something like this
![image](https://user-images.githubusercontent.com/33513626/233821540-f2fa64ce-66a3-4892-8540-31c9e8fb4fea.png)

**Comment by hagezi** [comment]
The domain has been on blocklists for several years because it is supposedly also used for tracking and I have not found any restrictions yet. However, when I look at the payload, I see no indication of tracking. Have also checked it on other sites that use Bitmovin.

The following issue confirms that there is no tracking:
https://github.com/easylist/easylist/issues/7999

I will remove the domain.

**Comment by notracking** [comment]
Thanks, fixed!
