### ISSUE TITLE
Allow icloud Private Relay

### ISSUE THREAD

**Issue by zeezeepiggy** [hagezi/dns-blocklists#983]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### Which blocklist(s) do you use?

Multi PRO

### Which domain(s) should be unblocked?

mask.icloud.com, mask-h2.icloud.com

### Why should the domain(s) be unblocked?

internet connection is lost due to iCloud Private Relay being blocked.

![IMG_0152](https://user-images.githubusercontent.com/27464836/235126950-5bd35014-4494-428f-abf4-7bc8df783ef2.jpeg)

![IMG_0153](https://user-images.githubusercontent.com/27464836/235127114-e6ca86ea-b903-4dec-9288-1e1d82ad6609.jpeg)

**Comment by hagezi** [comment]
Thanks, must have been an "accident" in the OISD. @sjhgvr
They will be removed immediately.

**Comment by sjhgvr** [comment]
> Thanks, must have been an "accident" in the OISD. @sjhgvr They will be removed immediately.

Correct. Already removed from oisd.

**Comment by hagezi** [comment]
Thanks @@sjhgvr. ;)

**Comment by devipasigner** [comment]
These domains should actually be responded with the NXDOMAIN code

**Comment by sjhgvr** [comment]
> These domains should actually be responded with the NXDOMAIN code

While I think I know what you mean .. (if these domains are allowed, the DNS blocking doesn't work because all traffic goes trough apple) and that's (most of the time) exactly the opposite of what one wants ..

One could use these lists network wide (in Pi-hole, Adguard Home, etc) .. and work for all devices on the network.
Let's say for some devices I don't want to use this list and want to use the icloud relay? I would not be abe to use it. Or friends come over and have their phones set up this way and make use of my wifi .. their internet would not function.

If we block this by default, we should block all VPN/Proxy etc by default as well.

**Comment by denis-g** [comment]
Now `mask-h2.icloud.com` is blocked.

**Comment by hagezi** [comment]
@denis-g not blocked in my lists, except in the bypass lists, where it also belongs.

**Comment by drybx** [comment]
It remains blocked in the DoH/VPN/TOR/Proxy Bypass list, right?

**Comment by hagezi** [comment]
Yes, that's the point of this list ...
