### ISSUE TITLE
Spotify Mobile App Payment Issue

### ISSUE THREAD

**Issue by DemirSe** [hagezi/dns-blocklists#991]
### Which AdBlocker/DNS cloud service do you use?

NextDNS

### Which blocklist(s) do you use?

Multi PRO++

### Which domain(s) should be unblocked?

pci.spotify.com

### Why should the domain(s) be unblocked?

It breaks credit card payment box in mobile app.

**Comment by hagezi** [comment]
Thanks, will be removed. Ping @bongochong

**Comment by hagezi** [comment]
fixed.

**Comment by bongochong** [comment]
Thank you @hagezi. Hectic weekend. I've always avoided Spotify like the plague, but it would be great to have some confirmation as to whether or not whitelisting this domain makes blocking of Spotify ads less effective. May have to mess around with the application myself, since I can't find much useful discussion of this domain in particular. Will ping you if I discover anything, and if there's no perceivable difference I'll whitelist this in a few days.
