### ISSUE TITLE
umami.is

### ISSUE THREAD

**Issue by StrangePeanut** [hagezi/dns-blocklists#998]
### Which AdBlocker/DNS cloud service do you use?

Other

### Other

pfBlockerNG

### NextDNS users only

- [ ] I have disabled the block page in NextDNS and confirm that the problem still occurs!

### Which blocklist(s) do you use?

Multi PRO

### Which domain(s) should be unblocked?

umami.is
www.umami.is
~~analytics.umami.is~~

### Why should the domain(s) be unblocked?

I am unable to access the documentation for Umami. ~~The demo site at https://analytics.umami.is/ is also inaccessible.~~

https://umami.is/ provides information on Umami, an open-source, self-hosted and privacy-friendly alternative to Google Analytics.

**Comment by hagezi** [comment]
Hi, thanks, it is an alternative to Google Analytics and belongs to the tracking category. Therefore, it is rather something for the personal allow list. It is included in many blocklists.

https://slayterdev.github.io/tracker-radar-wiki/domains/umami.is.html

`ads.google.*` is not Google Analytics. It is not included in light to pro plus because: https://github.com/hagezi/dns-blocklists#referral

**Comment by StrangePeanut** [comment]
Whoops I definitely meant Google Analytics, not Google Ads!

> https://slayterdev.github.io/tracker-radar-wiki/domains/umami.is.html

I understand `analytics.umami.is` being considered as a tracker, but what about umami.is which merely provides info and docs?

**Comment by StrangePeanut** [comment]
@hagezi looks like it was silently added back to the list 😕

**Comment by hagezi** [comment]
@StrangePeanut Sorry, my fault, fixed on next update.
